### ISSUE TITLE
Scaffold Codebase

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#1]
Scaffold out the codebase using https://github.com/unicef/etools-partner-reporting-portal as the base structure, but replacing following:

- polymer folder with react folder
- clean out django_api apps (since changing)
- Any naming changing needed (relevant to this project)

**Comment by lkolacz** [comment]
4 containers: db, proxy, frontend, backend

**Comment by lkolacz** [comment]
apps cleaned and user model added
