### ISSUE TITLE
Update Observations

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1007]
"Edit Observation" will become "Update Observation"

Instead of being able to edit the contents of the observation (+ more), the user will now be restricted to either invalidating or escalating it. 

Once their choice has been made, an additional comment field "Reason for Decision" will be generated and the content entered there will display in the expanded row details from the observation list view (See email from 4/26). 

Lastly, the email of the user creating the observation will automatically be populated in the Email field - or will need to manually provide it, depending on whichever makes more sense to build.

**Comment by kasialanecka** [comment]
Updating observation, starts here:
https://invis.io/BNGA4CB5AT3#/287010088_Agency_-_Partners_09

Filters and table content can be viewed here: https://invis.io/BNGA4CB5AT3#/287010090_Agency_-_Partners_11
