### ISSUE TITLE
Risk Category

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1008]
Next, the client communicated the need to categorize the risk. This will be done when a user creates an observation of either a Yellow Flag or Escalated Flag ONLY.

Once a flag is selected, they will be able to select the category of risk to apply to the observation. 

This Risk Category will need to be included in both the filter section of the Observation List page and then added to a column in the table list.

See email from 4/26

**Comment by kasialanecka** [comment]
@brandinalexander please send the email to me once again. Not sure if I have the correct one.

**Comment by kasialanecka** [comment]
Adding new observation with risk category, starts here: https://invis.io/BNGA4CB5AT3#/287010077_Agency_-_Partners_02_Add-Observ_01
