### ISSUE TITLE
Fix Partner-ID http header value not being passed properly to the backend

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1011]

**Comment by momimomo** [comment]
In what situation it's not passed? all request from partner portal have Partner-ID in header.
![Screen Shot 2018-05-23 at 11.55.48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a379ee0c2e54415b46be5d4a1f06a3a3dc78e2a436628f550eb8d564577dc13b16afba821fbf03bf72da1e85b7ea9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ff64de84955a715366af43b.png)
![Screen Shot 2018-05-23 at 11.55.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a379ee0c2e54415a4cbe5d4a1f06a3a3dc78e2a436628f550eb8d564577dc13b16afba821fbf03bf72da1e85b7ea9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5ff64de84955a7123663f43b.png)
![Screen Shot 2018-05-23 at 11.55.39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a379ee0c2e54415c47be5d4a1f06a3a3dc78e2a436628f550eb8d564577dc13b16afba821fbf03bf72da1e85b7ea9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca5ff64de84955a7123662f43b.png)
![Screen Shot 2018-05-23 at 11.55.43.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a379ee0c2e54415b4dbe5d4a1f06a3a3dc78e2a436628f550eb8d564577dc13b16afba821fbf03bf72da1e85b7ea9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ff64de84955a7123160f43b.png)

**Comment by maciej-jaworski** [comment]
Maybe it's fixed already with the other user changes, ok to mark it done for now.
