### ISSUE TITLE
Add AGENCY_OFFICE_ID  http header to requests for agency user

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1013]
Agency User info returned from `/api/accounts/me/` has been updated to return all offices user is a member of under `office_memberships` use that info to populate the header.

**Comment by momimomo** [comment]
Where is this used? Change implemented. (question by @kenzo23312 )

**Comment by maciej-jaworski** [comment]
Same as PARTNER_ID header should be passed to all authenticated api requests.

**Comment by maciej-jaworski** [comment]
Is this on a branch? Don't see it on develop.

**Comment by momimomo** [comment]
it's on 1014 PR

**Comment by momimomo** [comment]
I'll make a seperate branch just for that and PR

**Comment by momimomo** [comment]
It's on 1014 PR.
