### ISSUE TITLE
Fix agency user login

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1014]
Agency user login is currently not working, most likely due to changing how the output of `/api/accounts/me/` has changed to accomodate multiple offices per agency user.

This serializer change also affects following endpoints: 
- [x] `/agencies/<pk>/members/`
- `/projects/application/<pk>/feedback/` - provider
- [x] `/partner/<partner_id>/flags/` - submitter
- [x] `/partner/<partner_id>/flags/<pk>/` - submitter
- [x] `/partner/<partner_id>/verifications/` - submitter
- [x]  `/partner/<partner_id>/verifications/<pk>/` - submitter

**Comment by kenzo23312** [comment]
We are missing agency id and agency name fields in /accounts/me

**Comment by kenzo23312** [comment]
/agencies/<pk>/members/ - returns 403 for role ADMINISTRATOR
