### ISSUE TITLE
Freeze Observation Comment

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1021]
Once an observation has been posted, the comment should be frozen/grayed out, with the original timestamp, and not subject to further edit. The author of the observation, however, can add an additional comment to the previous observation, thus creating a comment thread.

https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96332293

**Comment by kasialanecka** [comment]
please check
