### ISSUE TITLE
Agency - CFEI: Display Attachment

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1024]
Reminder that if there was an attachment uploaded by the creator, then it should appear here.

https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96310063

& HERE:

https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96307291

**Comment by kasialanecka** [comment]
shown as example here: https://invis.io/97IHQR82MST#/289673825_Agency_-_CFEI_04
