### ISSUE TITLE
Observations: Sanctions Flow

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1043]
*Requirements:*

Ability to view potential matches on the UN Security Council Sanctions List and indicate if the organization or individual is ‘Not a true Match’ or a ‘Confirmed Match’.

On the instance when a partner matches with sanctions list, an observation (Yellow Risk) is generated from the system with the following criteria:
- The risk observation comment will display what criteria matched (Text String) with the Sanctions List.
- The risk observation will be categorized as "Sanctions Match".

Ability to restrict Partners that have a risk observation under the category of "Sanctions Match" from being selected, participating in the selection process by Agency Users. (i.e: Button will be removed).

Ability to ensure that the name of a CSO is not flagged in subsequent scans if the potential match on the UN Sanctions list was manually determined to be ‘Not a true match’.

**Comment by kasialanecka** [comment]
@brandinalexander the flow: https://invis.io/BNGA4CB5AT3#/299811708_Agency_-_Partners_02_Verified-When_Sanctions_Match (link to our private invision project, if confirmed I will update client's link)
