### ISSUE TITLE
Partners: Parent / Child Distinction

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1044]
**Description**

What happens if a child CSO is named differently than the HQ 

*Example:* In China, "Save the Children - China" could be named "Jiuzhu" - though it would not populate in the search for "Save the Children". 

Can we tuck the child CSO under the parent CSO someway that doesn't break the experience?

**Link**
https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=98219033

**Comment by kasialanecka** [comment]
@brandinalexander  maybe show Parent CSO name in expandable row for child CSO?

**Comment by kasialanecka** [comment]
Invision link: https://invis.io/TNJOO1QGMA5#/289673855_Agency_-_Partners_01
