### ISSUE TITLE
BUG - Cannot Create CFEI

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1055]
**W:** https://uat.unpartnerportal.org/login
**U:** unppunicef1@outlook.com
**P:** Unpp2017

**Steps to Re-create:**
- Login
- Click CFEI
- Click Create New CFEI
- Fill out CFEI
- Click Save

**Expected Result**
CFEI is Created

**Actual Result**
Error Message

**Comment by maciej-jaworski** [comment]
Blocked by #1064

**Comment by maciej-jaworski** [comment]
This environment is currently down, cannot login.
