### ISSUE TITLE
Fake data

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1063]
Let's clean up fake data users:

We should consider to make consistent (not random) users for both Agency / Partner

I think that we can limit number of created users and we can even make small description like 

fake-user-1 - WFH - Admnistrator
fake-user-2 - WFP - Basic Editor 
fake-user-3 - INGO Partner - Administrator 
fake-user-4 - INGO HQ reader 

etc.

Other data for created CFEI's DS.. data may stayed the same as now - random

Partner profile data - if possible we should create partners with completed profiles - there is no need to fill data than when we want to create UCN / submit CN etc.

**Comment by maciej-jaworski** [comment]
https://unicef.gitbook.io/unpp/technical-documentation/development-setup/development-data
