### ISSUE TITLE
Generation of CFEI and DS/R IDs

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1116]
UNPP currently generates IDs for open selection CFEIs and direct selections/retentions. It appears to be doing this in a sequential manner. For example, UNICEF Somalia recently posted CFEIs. The IDs assigned to these CFEIs are 18, 19, 20, 21 consecutively.

The IDs currently contain no other identifier. 

 It would be useful if, in ID generation for CFEIs and direct selections/retentions, the following fields were considered:

- Name of issuing agency (UNHCR, UNICEF, WFP)
- Name of issuing agency country office (Afghanistan, Zimbabwe)
- A unique number (possibly reflecting year)

The following ID structure is proposed for open selection CFEIs and direct selections/retentions:

https://www.evernote.com/l/AuVcTjF3jptEvIdTkypeiIfihI6zUVxm8As

***Examples:***

*The 1st CFEI/DSR posted by UNICEF Afghanistan in 2019 will be:*

- ***CEF/CHN/2019/001***

*The 50th CFEI/DSR posted by WFP Zimbabwe in 2020 will be:* 
- ***WFP/ZWE/2020/050***

**Comment by maciej-jaworski** [comment]
Backend pretty much done. LMK if any other endpoints need this info.
