### ISSUE TITLE
Text Content Updates

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1137]
- [x] **Reword:** Select type of organization
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96299399
- [x] **Replace with:** Fill the partner declaration
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96301446
- [x] **Relabel:** Expressions of Interest
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96301830
- [x] Replace: In order for this direct selection/retention to become active, it must be sent to the focal point for publication.
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96308227
- [x] **Replace:** This direct selection/retention was sent to the focal point for review and issuance to the selected partner.
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96309120
- [x] **Message to Display:** "Are you sure you want to publish this direct selection/retention?" "Please confirm that this direct selection/retention should be published. An e-mail notification will be sent to the selected partner."
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96309372
- [x] **Message to Display:** "Are you sure you want to add an observation to this profile?" "An observation can be added to record brief notes on past collaboration, risk or other key issues."
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96318842
- [ ] **Modal Display:** "Having reviewed the risk observation escalated by the Country Office, UN HQ has determined that:"
1. The risk is deferred to the Country Office for local decision-making
2. No partnership should take place with the flagged organization.
Comments (optional)
Attachment (optional)
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96332474
- [x] **Page Description to Display:** "Select filters to generate reports on partners and partner contact information or a map of partner presence."
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96333317
- [x] **Filter to Display:** "Registered in country"
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96333431
- [x] **Page Description to Display:** "Select filters to generate a report or map of CFEIs and direct selection/retention."
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96334075
- [x] **Page Description to Display:** "Select filters to generate a report on partner verification and observations"
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96334393
- [x] **Change Text:** Instead of calling this "Organization Profile Summary," can you just call it "Profile Summary"?
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=97216444
- [x] The word 'expression' should be 'expressions'
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=96302047
- [x] Organization should be spelled with a 'z' and not 's'
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=97955540
- [x] 'Expressions of Interest' as the results include DS/R and is not only CFEI
- https://project.invisionapp.com/d/main#/projects/prototypes/13903744/comments?inbox=true&inboxProjectID=13903744&inboxConversationID=97956546

**Comment by momimomo** [comment]
Updated all components that were already in the codebase.
