### ISSUE TITLE
Project/CFEI Details:Applications Create API

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#115]
Create/POST API for the following endpoint:
**/projects/:id/applications/**

**Description**
This will allow a Partner to submit/create an application for an open CFEI. The only required information from their end is a CN (file). 

There should only be one application allowed per partner per EOI/project. 

**Relevant wireframes**
https://invis.io/32CLE7585#/242436061_EIO-Partner-Application_01 (partner user submitting application for open cfei)
https://projects.invisionapp.com/share/9VCMWHXJS#/screens/244964030 (edit screen is missing, but will need ability to create more applications for a direct selection. This is for agency user)

**Comment by lkolacz** [comment]
for open post:
```
{
    "partner": Partner.objects.first().id,
    "cn": cn_template,
}
```
for direct selection add another partner
```
{
    "partner": Partner.objects.last().id,
    "ds_justification_select": JUSTIFICATION_FOR_DIRECT_SELECTION.known,
    "ds_justification_reason": "a good reason",
}
```
url: `/api/projects/1/applications/` where pk=1 is from EOI
