### ISSUE TITLE
Clear focal point filed on 'Clear' action

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1157]
- [x] Focal point field is not clearing after form 'Clear' action.

Probably we should use initialMultiValues to get 'clear' working.

![Screen Shot 2018-06-11 at 1.43.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599e8973fd1580001aaed984/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f26b7191a379f116284f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ee4d4385b7dce3416aabf811dbf01ba228e1dd4e7bc8b1ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df443e64c52a116306aee752431.png)

**Comment by rkrupinski** [comment]
PR: https://github.com/unicef/un-partner-portal/pull/1172
