### ISSUE TITLE
DS/R Enhancement: Red Flag Eligibility

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1165]
**Trello Ticket:**
https://trello.com/c/iQlWs10w/78-ds-frontload-with-cr

**Enhancement:**
CSOs with verified status but a red flag should not be eligible for direct selection

**Comment by maciej-jaworski** [comment]
@kenzo23312 For DSRs filter out `&no_flags=FL4_Red` when getting partners for autocomplete
