### ISSUE TITLE
DSR - bugs

### ISSUE THREAD

**Issue by kasialanecka** [unicef/un-partner-portal#1175]
- [ ] I was able to create new DS/R without selecting Partner but I had to provide justification to save a modal  // Basic Editor

- [x] Missing option in "justification" dropdown - "Partner retention" // Basic Editor

- [x] Published DSRs are not shown on the list when "Active" filter selected // Basic Editor

- [x] Information that Partner accepted or declined the offer is not shown on Agency side (still showing "Waiting for Partner's acceptance" status). But when "Finalize modal" is open, all options are available.
<img width="283" alt="screen shot 2018-06-13 at 13 50 37" src="https://user-images.githubusercontent.com/25788754/41350161-79220ef4-6f12-11e8-8e0b-5b6150f25929.png">

- [x] When Partner changes decision from accept to decline and sends this change, nothing happens - on Partner side the info is shown "Selection confirmed" and on the list status of this DSR is "Selecton Accepted"
<img width="534" alt="screen shot 2018-06-13 at 14 01 11" src="https://user-images.githubusercontent.com/25788754/41350092-441de1e2-6f12-11e8-845a-a725f9f58629.png">

- [x] is "Application Successful" correct Partner status (Draft of DSR is created and to be published, but not published yet and Partner is not notified yet):
<img width="223" alt="screen shot 2018-06-13 at 14 51 07" src="https://user-images.githubusercontent.com/25788754/41352298-66ae0000-6f19-11e8-9663-c50eedac2ab2.png">

- [x] we can't have two "cancel" buttons that mean different things in one modal:
<img width="545" alt="screen shot 2018-06-13 at 14 57 33" src="https://user-images.githubusercontent.com/25788754/41352620-43f6703c-6f1a-11e8-9b0c-b6852d89e00d.png">

- [ ] sorting columns in table (list of all DS/Rs) is not working

**Comment by maciej-jaworski** [comment]
Sorting columns is most likely related to #1177

**Comment by maciej-jaworski** [comment]
For the partner has accepted, then changed decision to decline backend returns proper info, frontend just doesn't handle that case
It's also not properly handled on the agency side with `Waiting for Partner's acceptance.` displayed.
<img width="1053" alt="screen shot 2018-06-14 at 09 25 19" src="https://user-images.githubusercontent.com/1492815/41397725-6a0ac80e-6fb5-11e8-9581-96f466962275.png">

**Comment by maciej-jaworski** [comment]
While values for DSR justification are returned from the global config endpoint, they are hardcoded on the frontend, please fix to use backend provided values.
