### ISSUE TITLE
UCN issues

### ISSUE THREAD

**Issue by kasialanecka** [unicef/un-partner-portal#1180]
- [x] on the list with all UCNs (on Partner side) there's no info about status (draft/submitted)

- [x] When UCN is a draft, submission date is shown on the list (maybe not to show any date, which would indicate that this is a draft and first issue would be solved?)

- [x] On agency side - when I want to view UCNs, this is what I see:
<img width="401" alt="screen shot 2018-06-14 at 14 25 57" src="https://user-images.githubusercontent.com/25788754/41413597-d8ea2f98-6fe3-11e8-9724-d2f2502ea8f1.png">

- [x] The same issue as above on Partner side - logged in as Admin (Partner) - check Kasia's project #5

**Comment by maciej-jaworski** [comment]
Backend stuff should be fixed.
