### ISSUE TITLE
CFEI permissions

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1192]
- Assess Applications Submitted for CFEI Published by Own Agency
- Approve Partner Selection for CFEI Published by Own Agency
- Finalize CFEI Published by Own agency

**Comment by maciej-jaworski** [comment]
`CFEI_REVIEW_APPLICATIONS`
`CFEI_SELECT_RECOMMENDED_PARTNER`
`CFEI_FINALIZE`
