### ISSUE TITLE
Preserve Reviewer Privileges

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1194]
**Summary:**
Preserve Reviewer Privileges

**Steps to Reproduce**
www.unpartnerportal.org
[EMAIL]
[PASSWORD]
Go to CFEIs List 
Filtered (Finalized)
Select CFEI
Select Preselected tab
Select an application and scroll down to reviewers, scores, and notes (MISSING)
Select Results Tab
Review Scores of selected CSO (MISSING)
Show Reviewers (MISSING)

**Expected Results: **
Select a reviewer for a CFEI Application and allow the reviewer to add scores and system to preserve information.

**Actual Results**
The review is not being saved.
The system removes information on scoring and evidence of reviewer selection or reviewer's actions.
The user is not being kept as a reviewer and the scores and associated results are not preserved.

**Demo Video Link**
https://drive.google.com/open?id=1bPtCmGP5ViwAnf1vQF17mLGKbi3HXxGr

**Comment by brandinalexander** [comment]
Added link to a video demo of the issue in the description.

**Comment by maciej-jaworski** [comment]
<img width="1429" alt="screen shot 2018-06-22 at 13 51 47" src="https://user-images.githubusercontent.com/1492815/41775280-9fac022e-7623-11e8-822f-fabc62a52579.png">
Selected CFEI has no reviewers, you can see the review progress states 3/0 possible.
IDK what is the flow that made this possible, is there a bug that wipes the reviewers, or was the CFEI altered from django admin, breaking the flow / UI? Hard to say at this point Is there any more information about process applied here? Deleting reviewers works fine where I tested it.

**Comment by brandinalexander** [comment]
Apparently, there is a delay in the issue and when it is being presented. Afer a user logs out or finalizes a CFEI, their reviews will be removed and they will be prevented from making changes at this point.

**Comment by maciej-jaworski** [comment]
According to Nadine, reviewers are being removed from CFEI repeatedly, even after being readded - check how exactly the relationship is being updated

It is possible that frontend sends and empty list / null and triggering wipe of the relationship - check that too.

**Comment by maciej-jaworski** [comment]
Still couldn't reproduce this. Possible it's a side effect of some frontned update.
Open a PR #1217 to remove the ability to wipe reviewers alltogether.
