### ISSUE TITLE
Partner Creation & User Registration Steps

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#12]
The following is the interaction / experience of the screen, without integrating the API. 

A user should be able to follow the steps on the registration screen to successfully create a partner and a registered user (for that partner). 

The registered user information will be captured from the email, password on the steps. They will automatically become the admin of the partner. 

**Restrictions**
- If type International (NGO) organization is awarded and Country is indicated, the user should NOT be allowed to proceed 
- If the user responds NO to any of the Harmonized Due Diligence questions, they should not be allowed to proceed. 

Upon successful registration, the user will be directed to the profile complete view. 	

**Invision Links:**
- Initial Registration Prompt 
- National NGO Selection
- International NGO Selection
- Prompt that HQ Registration Needs to be done First
- Head of Organization Validation
- Harmonized Due Diligence Declaration 
- Account Creation
- Final Registration Confirmation

First screen starts here: https://projects.invisionapp.com/share/T4CGYCOAP#/screens/242435613

**Comment by marcindo** [comment]
@elyk we don't have any initial prompt in wireframe, you want me to cook up something simple or just start at the very first invision screen? 

Also I'd like to note that this feature utilizes stepper component which is not yet [migrated ](https://github.com/callemall/material-ui/issues/4799) to material-ui@1.0 so I'll use older version for the time being, could also help folks with migrating it.

**Comment by elyk** [comment]
@marcindo let's just start at the very first invision screen. 

Ok cool - will this lose our ability for leveraging the grid?

**Comment by marcindo** [comment]
Turns out using the old one is very tricky and would require some big changes which is imo not worth it. I found incomplete implementation of the stepper that I'm going to add as custom asset to our project. This is beneficial because later on we have some mutations of stepper in other forms so we would have to add custom element anyway

**Comment by marcindo** [comment]
done in #25
