### ISSUE TITLE
CFEI edit bugs

### ISSUE THREAD

**Issue by momimomo** [unicef/un-partner-portal#1205]
Backend:
- [x] Editing partner in DS/R draft on patch results in `404: detail not found`

- [x] Allowing for patching locations in draft Open CFEI and DSR

- [x] Allowing for patching sectors in CFEI and DSR

- [x] Expose `weight: <int>` field in `assesments_criteria`at `/api/projects/open/`

Frontend:
- [x] Add weighting to edit modal and partner info (backend first)

- [x] If DS/R attachment is string, remove from payload

- [x] Link `Other information` in edit to redux forms

- [x] Switch date layout in date edit modal

**Comment by maciej-jaworski** [comment]
Make sure to fix frontend to send `specializations` same way as they're being sent when creating - as list of ids, not the complete deserialized structure.

**Comment by maciej-jaworski** [comment]
`Expose weight: <int> field in assesments_criteria at /api/projects/open/`

This information is returned from the project details view, it's not needed on the list view

**Comment by momimomo** [comment]
Problem still persists - specializations structure:
![Screen Shot 2018-06-27 at 10.11.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f46b7191a379ef0c2a50415e4fbe5d4a1f06a3a3dc78e2a436628f550eb8d564577dc13b16afba821fbf03bf72da1e85b7ea9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb58f643e64c57a5143661f43b.png)

and the error:
![Screen Shot 2018-06-27 at 10.11.21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abba0fa42a63c001483a918/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f46b7191a379ef0c2a50415d4fbe5d4a1f06a3a3dc78e2a436628f550eb8d564577dc13b16afba821fbf03bf72da1e85b7ea9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb58f643e64c56a1163f66f43b.png)
