### ISSUE TITLE
UNHCR Request

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1216]
Request for Tivix to provide a schema of the target DB. This can be done in two ways:

- DB dump of an empty ‘target’ DB
- The SQL scripts to recreate the necessary tables. I.e. create table PartnerProfile

**Comment by maciej-jaworski** [comment]
We're using [PostgreSQL](https://www.postgresql.org/), attached the most recent db create script.

[UNPP-db-only.sql.zip](https://github.com/unicef/un-partner-portal/files/2153958/UNPP-db-only.sql.zip)
