### ISSUE TITLE
V&O Bugs / issues

### ISSUE THREAD

**Issue by kasialanecka** [unicef/un-partner-portal#1239]
- [x] `BACKEND` What about "Users" tab in Partner detailed screens? Should we remove this tab (it's empty now) or provide not editable list of users?

`Should the Tab 'Users' in partner details section be removed?`
No. On the UN side, the UN user should be able to view, but not edit, a CSO’s users

- we need endpoint for this 

<img width="1011" alt="screen shot 2018-07-11 at 13 52 02" src="https://user-images.githubusercontent.com/25788754/42569673-9e276c7a-8511-11e8-88e8-b584ddfa2880.png">

- [x] Lack of information about Potential true match on sanction list on overview page (screenshot from invision below)
<img width="433" alt="screen shot 2018-07-11 at 11 44 03" src="https://user-images.githubusercontent.com/25788754/42564054-05380846-8500-11e8-87c5-7457dfc9988f.png">

- [x] `BACKEND` Shouldn't Basic Editor have access to "Observations" tab, but see only rows with "sanction" flags? Now, there's no place in the app to do the sanctions check, as follows:
<img width="1171" alt="screen shot 2018-07-11 at 13 40 02" src="https://user-images.githubusercontent.com/25788754/42569438-cb58efe4-8510-11e8-8a75-54721e354e6a.png">

- [x] `BACKEND` Strange flow: HQ editor can escalate yellow flag to HQ (= to himself) and while editing he can deffer back this flag? 

UNICEF Response: 
`Yes HQ editor should have the option to escalate as per the current requirements, which align with Brandin’s recommendation during the recent end of sprint demo` 

<img width="544" alt="screen shot 2018-07-11 at 15 05 56" src="https://user-images.githubusercontent.com/25788754/42573320-12d81b5a-851c-11e8-818c-f2738d878b31.png">

- [x] `BACKEND` `Should the 'Sanction Match' be counted as a yellow flag in counter?`
UNICEF Response: Yes
<img width="458" alt="screen shot 2018-07-11 at 15 28 19" src="https://user-images.githubusercontent.com/25788754/42574783-8dc74ab8-851f-11e8-9b1f-1d339c234dac.png">

- [x] `BACKEND` Filter not working:
<img width="635" alt="screen shot 2018-07-11 at 16 57 36" src="https://user-images.githubusercontent.com/25788754/42580793-a4de41a0-852b-11e8-9b5d-7fe6f499df43.png">
<img width="518" alt="screen shot 2018-07-11 at 16 57 46" src="https://user-images.githubusercontent.com/25788754/42580797-a816a484-852b-11e8-860d-9bbd1530eb17.png">
<img width="1276" alt="screen shot 2018-07-11 at 17 00 06" src="https://user-images.githubusercontent.com/25788754/42580931-f0e9b2fa-852b-11e8-8e9d-32bb1d8c6a15.png">

- [x]  Changes in modal window when verifying a Partner (info about flags, checkbox at the bottom): https://projects.invisionapp.com/share/E5MW4VXNW83#/screens/287696264

**Comment by maciej-jaworski** [comment]
> BACKEND Filter not working:

NOT a backend issue, @kenzo23312 didnt hook the filters up properly from the frontend

**Comment by maciej-jaworski** [comment]
> we need endpoint for this

`/partners/<pk>/members/` has always been in place

**Comment by maciej-jaworski** [comment]
Backend items should be done.
