### ISSUE TITLE
Pilot Enhancements

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1243]
*C F E I*
https://docs.google.com/document/d/1ZFAYDUlXRQsI6cO86I700Q7Ld4TjhR9onhU9sSDCHf0/edit?usp=sharing

- [ ] - "[CFEI: ASSESSMENT] Preselected List tab: Add a “Complete Assessment” button on the preselected list tab. Once a reviewer has completed the assessment of all applications, the user clicks the tab to indicate the review process is complete."

- [ ] - "[CFEI: ASSESSMENT] Preselected List tab: Add a new column in the CFEI creator or focal point view titled “Recommend Partner”. In each row, add a “recommend” button, where the creator or the focal point can nominate the best CSO/concept note. This recommend button is disabled until all reviewers have selected the “complete assessment” button"

**Comment by kasialanecka** [comment]
### **Complete Assessment**

**v1** (3 screens, linked):
https://invis.io/E5MW4VXNW83#/309375086_Agency_-_CFEI-Preselected-Complete-Assessment_01

**v2**  (2 screens depending what should be shown in the menu, no links):
https://invis.io/E5MW4VXNW83#/309375107_Agency_-_CFEI-Preselected-Complete-Assessment_04
https://invis.io/E5MW4VXNW83#/309375108_Agency_-_CFEI-Preselected-Complete-Assessment_05

### **Recommend Partner**

**v1** (4 screens, linked):
https://invis.io/E5MW4VXNW83#/309375207_Agency_-_CFEI-Preselected-List_Recommended_01

**v2** (4 screens, linked):
https://invis.io/E5MW4VXNW83#/309375239_Agency_-_CFEI-Preselected-List_Recommended_05

**Comment by kasialanecka** [comment]
@kenzo23312 could you look at those versions if there's sth hard to implement and point it out?

**Comment by brandinalexander** [comment]
@kasialanecka Very nice... will wait for @kenzo23312 's reply before presenting to UNICEF.

Would be good to have an answer by tomorrow's demo so we can present, then.

**Comment by kasialanecka** [comment]
@brandinalexander After talking with @kenzo23312 we could go with option 1 in both cases. The problem we have now - we don't have the option to edit already added review. It's a bug and I've created a ticket for it. We need to have the option to edit reviews, because otherwise "complete assessment" button is useless (in modal window we want to display information that after clicking this button, user cannot edit his scores anymore).
