### ISSUE TITLE
Prescreening

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1257]
New Fields in `legal status` section during registration - those fields should be pre populated in partner profile 

- country_code_origin
- year_establishment

- registration_to_operate_in_country:
YES:
- registration_date
- registration_number
- authority_name (New field in Partner Profile/ identification section)
- expiration_date (optional) (New field in Partner Profile/ identification section)
NO:
- registration_comment

- have_registration_doc:
YES registration_doc
NO: registration_doc_comment

- have_gov_doc: 
YES: gov_doc
NO: gov_doc_comment

- have_ref_letter
YES: ref_letter
NO: ref_letter_comment

**Comment by maciej-jaworski** [comment]
According to requirements:
> Once the CSO is in the portal, the documents uploaded will pre-populate the legal status section
of the portal and cannot be edited. Users will have the option to ‘add new’ section to upload
updated versions of the documents, as relevant.

Meaning that these document fields will have to moved to M2M type of relation.

**Comment by maciej-jaworski** [comment]
All the changes pushed to `1257-prescreening` branch, work can continue there.

**Comment by maciej-jaworski** [comment]
```new documents (e.g. those added at any time after the registration stage) can be deleted by the partner.```
