### ISSUE TITLE
Pilot: Registration

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1259]
Change in order/sequence of the partner declarations (see declarations)
- [x] `Frontend`
------------------------------------------------------------------------------
For INGOs, the declaration made by the parent/HQ at registration populates all the child profiles in the “other information” tab
- [x] `Backend`
- [x] `Frontend`
------------------------------------------------------------------------------
The “Terms of Use” and “Privacy Policy” will be a hyperlink that when clicked will direct the user to the UN Partner Portal landing page
- [x] `Frontend`
------------------------------------------------------------------------------
Addition of a new partner declaration question
- [x] `Frontend`
------------------------------------------------------------------------------
A well formatted copy (PDF) of the partner declaration saved in ‘Other Information’ tab of the CSO’s profile, upon completion of the registration workflow (see example)
- [x] `Backend` 
- [x] `Frontend`

------------------------------------------------------------------------------
 A new section after “Provide email and create password” named “Terms of Use” and “Privacy Policy”. (see mockups). The register button becomes activated only when the user agrees to the terms of use.
- [x] `Frontend`
------------------------------------------------------------------------------
On first log in, include a statement on terms of use (see mockups)
- [x] `Backend`  ?
- [ ] `Frontend`

**Comment by brandinalexander** [comment]
**Question**
`For INGOs, the declaration made by the parent/HQ at registration populates all the child profiles in the "other information" tab` - how UNICEF want to present this as a single button as download or?

**Comment by maciej-jaworski** [comment]
Added `accepted_tos` to profile and /me endpoint, This can be used to track whether TOS need to be displayed - last point.

**Comment by maciej-jaworski** [comment]
Partner endpoint has `registration_declaration` added, this is automatically filled in from HQ for INGOs
