### ISSUE TITLE
Pilot: Partner Profile pt 2

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1265]
"[Contact Information: Head of Organization] 
Place “Head of Organization” subsection before “Key Personnel” Section

- [x] `Frontend`

------------

• Users should have the ability to indicate whether the head of organization is (a) a member of the board of directors and (b) an authorized officer

- [x] `Frontend`
- [x] `Backend`
New fields: 
- is_authorized_officer
- is_board_member

------------

• INGO children/Country offices should have the ability to edit the head of organization pulled from the HQ profile to update it to the head in the local country of operation

- [x] `Frontend`

------------

• Users should be able to ‘add new’ head of organization to reflect staffing changes over time. When ‘add new’ head of organization subsection is selected, the new details entered will be by default seen as the current head of organization. The portal will maintain a continuous audit trail of previous heads of organization.

- [x] `Frontend`
- [x] `Backend`
New fields: 
- organization_heads (same structure field as `directors` or `authorised_officers` )
------------

"
Ability to download a well formatted PDF copy of the completed profile. This functionality should be present for both the CSO and the staff. Restriction: CSO can only download its own profile and that of the HQ.

- [x] `Frontend`
- [x] `Backend` should we generate this report on backend ?
------------

**Comment by maciej-jaworski** [comment]
Organization head changes added on `1265-partner-org-head-changes` branch

**Comment by maciej-jaworski** [comment]
Partner details export available @ `/api/partners/<pk>/?export=pdf`
