### ISSUE TITLE
BUG:  Unable to View Published CFEI from another agency

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1277]
**Summary:** 
Unable to View Published CFEI from another agency

 

**Steps to Reproduce:**

- Login to TivixLabs

- User Name: agency-1-editor@wfp.org

- Navigate to Expressions of Interests. In the filter select another agency (UNICEF or UNHCR) and enter the search. In the list, select a published CFEI to view its information.

**Expected Results:**
CFEI overview page should show.
 

**Actual Results: **
Message: Couldn’t load this page (see images below)

![unnamed-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46fd9a94228f86adc2b8fd0fe64de29b234324676b5ee17e29d0e67ce61a225659584dae41585f46f9abd87aa6b76a62964e49bc8f3900299f7744eeaa880dbe06b0218e4c86b3b58a4dc6e13925e299c2.png)
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51fa7e75d1ba70e6152d565c5d4eac415a5a16ada8892af0a42062c80d55b98e30063e937f03a6aa8318b500bf23884a8cb6bd8c45c3e13537aa.png)

**Comment by maciej-jaworski** [comment]
This is not a bug, this was probably tested when staging was down.
