### ISSUE TITLE
BUG: Ability to View Verification Comments on a Partner

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1278]
**Summary:** 
Ability to View Verification Comments on a Partner

**Steps to Reproduce:**

- Login to TivixLabs

- User Name: agency-1-editor@wfp.org

- Password: test

- Navigate to Partners, select any partner in the list, with verified status. Select the verification tab. Expand verification.

**Expected Results:**
Verification and Observation tabs should be hidden from basic editor and reader

 
**Actual Results:**
The user could view the verification comments and who performed the verification (see images below)
![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51fa7e75d1ba70e6152d565c5d4eac415a5a16ada8892af0a42062c80d55b98e30063e937f03a6aa8316b500bf23884a8cb6bf8c4ec7e13937aa.png)

**Comment by maciej-jaworski** [comment]
> Verification and Observation tabs should be hidden from basic editor and reader

This has not been specified before.
Not actually a bug since comments are removed from the view.

@kenzo23312 Please hide the tabs from users without `VIEW_PROFILE_OBSERVATION_FLAG_COMMENTS` permissions

**Comment by maciej-jaworski** [comment]
> Verification and Observation tabs should be hidden from basic editor and reader

According to permissions matrix Basic Editor needs to have access to perform actions on sanctions matches.

<img width="1372" alt="screen shot 2018-08-14 at 08 35 41" src="https://user-images.githubusercontent.com/1492815/44075469-305174a6-9f9d-11e8-9f8d-86f52eb827de.png">

As mentioned before comments are hidden, as requested.
Further information can be hidden based on permissions but we **cannot completely hide tabs for editor basic**.

**Comment by brandinalexander** [comment]
**Please see UNICEF's Reply**
```The basic editor does not have any permissions for observations. Therefore, for the sanctions matches, only the advanced editor can confirm or deny.```
