### ISSUE TITLE
New CFEI finalisation flow

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1286]
child of #1270 
blocked by #1285 

- Remove the “Select” button from the CSO application page
  - [x] Frontend

- Preselected List tab: Add new column in the CFEI creator or focal point view titled “Recommend Partner”. In each row, add a “recommend” button, where the creator or the focal point can nominate the best CSO/concept note. This recommend button is disabled until all reviewers have selected the “complete assessment” button
  - [x] Backend
  - [x] Frontend

- The CFEI creator or focal point can ‘recommend’ one or more CSOs for a CFEI
  - [x] Backend
  - [x] Frontend

- A user cannot recommend a CSO until all reviewers have completed their assessments i.e. clicked the “complete assessment” button
  - [x] Backend
  - [x] Frontend

- A CSO can only be recommended from the pre-select page
  - [x] Frontend

- Once the recommend button is selected, the user is directed to the Results tab where they will be required to fill in the results summary
  - [x] Frontend

- Once all the required sections are complete, the “send” button is enabled for basic editors or PAM users. If the creator is an advanced editor, the user will have the “select” button enabled
  - [x] Backend
  - [x] Frontend

- Once the send button is selected, a modal is displayed requiring the user to confirm that they want to send the recommended CSOs to the advanced editor/MFT user, informing them that the advanced editor/MFT user will receive a notification of the recommendation.
  - [x] Frontend

- When a recommended partner is sent to the advanced editor/MFT user, the user can no longer make edits to the review summary or change the recommendation
  - [x] Backend
  - [x] Frontend

- Once a CFEI has been sent to the advanced editor or MFT user for selection, the CFEI creator or focal point can no longer add a reviewer to the CFEI
  - [x] Backend
  - [x] Frontend

- The advanced editor/MFT user will receive a notification when the recommendation has been sent to them
  - [x] Backend

- The advanced editor/MFT user, from the results tab, can either “Select” the recommended partner(s) or go to the pre-selected tab, recommend another CSO and then select them.
  - [x] Frontend

- The date the partner was ‘selected’ and selected by should be captured in the recommended partner section.
  - [x] Backend
  - [x] Frontend

- If a CSO declines selection on a CFEI, once the UN user is notified of this declination, the CFEI creator or focal point can recommend and select another partner from the pre-select list. The user however, cannot select again the CSO that declined selection.
  - [x] Backend
  - [x] Frontend

- Once a partner is “Selected” there will be a modal where the advanced editor/MFT user will give a justification for selection (required).
  - [x] Backend
  - [x] Frontend

- Results tab: The results tab will have the following sections:
  - [x] Review summary: The results summary is now required to be filled before the user can ‘send’ the recommended partner(s) to the advanced editor or MFT user for ‘Selection’
  - [x] Recommended Partner(s): This is the present “Selected Partners” section. It is a subset of the pre-select list that were recommended. Expanding this section displays the criteria for assessment and the average score the CSO received for each criteria and the total average score. It also contains the notes from each reviewer.
  - [x] The user can withdraw a recommendation from this section.
  - [x] Preselected Partners: This is a new section that contains the subset of CSOs from the pre-selected lists who were not recommended. Like the Recommended partners section, when expanded it displays the criteria, average score per criteria, total average and reviewer(s) notes

**Comment by maciej-jaworski** [comment]
- New application status added - `('Rec', 'recommended', 'Application Recommended')`
- Preselected tab needs to show bot Preselected and Recommended status applications
- Recommending happens through updating application status
- Cannot recommend until application `assessments_marked_as_completed` is true
- `sent_for_decision` field added to EOI model to lock review summary and editing reviewers
- POST `/api/projects/<pk>/send-for-decision/` to be used to send to focal point for decision making

# Test Scenario 1
- Basic Editor: creates Open CFEI
- Partner: Applies
- Basic Editor: Application is preselected
- Reviewer: reviews
- Reviewer: complete reviews
- Basic Editor: Application is recommended
- Focal Point - Editor Advanced accepts recommendation
- Partner accepts
# Test Scenario 2
- Basic Editor: creates Open CFEI
- Partner1: Applies application1
- Partner2: Applies application2
- Basic Editor: application1 is preselected
- Reviewer: reviews all applications
- Reviewer: complete reviews
- Basic Editor: Application1 is recommended
- Focal Point - Editor Advanced recommends application 2 instead and accepts the recommendation
# Test Scenario 3
- Basic Editor: creates Open CFEI
- Partner1: Applies application1
- Partner2: Applies application2
- Basic Editor: application1 is preselected
- Reviewer: reviews all applications
- Reviewer: complete reviews
- Basic Editor: Application1 is recommended
- Focal Point - Accepts recommendation
- Partner1 declines selection
- Application2 is recommended and picked

**Comment by kenzo23312** [comment]
1. Review summary who should add / edit - anyone who has permission / after sending basic editor - cant edit summary / should be editable until partner accepted 
2. Retract selection - where
3. Send feature - general 
4. Edit reviewers - what with recommended partners / applications = recommend
5. Recommend without any assessments completed - no reviewers - at least 1 
6. Unrecommend on preselected list 
7. Results tabs select -> rectract
8. Preselected -> short list
9. multiple selections
