### ISSUE TITLE
Edit Partner HQ Profile

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1289]
**Summary:** Able to edit the HQ profile of partner organization

**Steps to Reproduce:**
- Login to UAT Environment

- User Name: partner-ingo-1-reader@partner.org

- Password: test

- Navigate to profile page, select HQ profile, select edit.

- Toggle into country office profile, select profile, select edit.

**Expected Results:**
The reader should not have the ability to edit the HQ or any country office’s profile. Also the user management tab should not be there

**Actual Results: **
Edit button enabled (see images below)
![unnamed.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51fa7e75d1ba70e6152d565c5d4eac415a5a16ada8892af0a42062c80d55b98e30063e937f03a6aa801cb500bf23884686b7bc8c4fc7ed3f37aa.jpg)
![unnamed-1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46fd9a94228f86adc2b8fd0fe64de29b234324676b5ee17e29d0e67ce61a225659584dae41585f46f9abd87aa6b76a62964e49bc8f3900299f7744eeaa880dbe08b0218e4c86bfbf8b4cc6eb3a21e099c2.jpg)

**Comment by maciej-jaworski** [comment]
This is a frontend only issue.
