### ISSUE TITLE
Partner Observation for Pending Verification

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1290]
**Summary:** Unable to add an observation to Partner with status pending verification

**Steps to Reproduce:**
- Login to UAT Environment

- User Name: agency-1-editor-hq@unicef.org

- Password: test

- Navigate to partner page. Select a partner with status, pending verification. Try to add observation

**Expected Results:**
User should be able to add an observation to the Partners profile

**Actual Results: **
Warning message telling the user they need to first verify the partner (see image below)

![unnamed.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51fa7e75d1ba70e6152d565c5d4eac415a5a16ada8892af0a42062c80d55b98e30063e937f03a6aa8317b500bf23884686b7b98e48c2ef3e37aa.jpg)

**Comment by maciej-jaworski** [comment]
Nothing on the backend does this sort of check, should only be frontend issue.
