### ISSUE TITLE
Partner / User Registration API

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#13]
We need a single endpoint that will account for this registration process:

https://projects.invisionapp.com/share/T4CGYCOAP#/screens/242435613

This endpoint will be special in the fact it should create:
- User
- Partner
- PartnerProfile
- PartnerMember 

The above needs to be created atomicly, hence all in one request.

**Comment by lkolacz** [comment]
Surething !!!
I will make a transaction so we will not worry about data integration if something will fail for any reason ;-) .. all those object will be created in one request :)
