### ISSUE TITLE
HQ / Country Profile - profile details

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#130]
**#Identification**

- missing API `Registration of organization` for country
- missing Governing `have_doc_govern` and `govern_doc`
- missing `comment` in registration section - `If no, please comment`

**#Contact informations** 
- Missing `Does your organization have a board of directors?` in Authorized partners section. 

**#Mandate and mission**  
- Ethics missing fields for comments `ethic_safeguard_comment` and `ethic_fraud_comment`
- typo `country_presents` -> `country_presence`
- Missing fields  and UI section in `country_presence` for country: 
     - Location of Office
     - Does your organization have more than one office in country of operation?
     - Location of field office(s) in the country of operation
     - Number of staff in country
     - Briefly describe the organization's engagement with the communities in which you operate

**#Project Implementation** 
- API missing Audit comment sections for fields:
   - `regular_audited`,  
   - `major_accountability_issues_highlighted` - change name currently `comment`, 
- API missing `Banking information` for country

**Keep fields naming unique.**

Link for missing fields for country: 

https://docs.google.com/spreadsheets/d/1dpBECNT5eMwMB5PkV0SlaxULV7IlnACRyRM0IiI7bh0/edit#gid=0

**Comment by lkolacz** [comment]
> **#Identification**
> 
> - missing API `Registration of organization` for country
> - missing Governing `have_doc_govern` and `govern_doc`
> - missing `comment` in registration section - `If no, please comment`

_add and rename fields, section registration of organization looks_

```
    # Registration of organization
    year_establishment = models.DateField(verbose_name='Year of establishment')
    have_gov_doc = models.BooleanField(default=False, verbose_name='Does the organization have a government document?')
    gov_doc = models.FileField(null=True)
    registration_to_operate_in_country = models.BooleanField(default=True)
    registration_doc = models.FileField(null=True)
    registration_date = models.DateField(auto_now_add=True)
    registration_comment = models.CharField(max_length=255, null=True, blank=True)
    registration_number = models.CharField(max_length=255, null=True, blank=True)
```

**Comment by lkolacz** [comment]
changes in code review

**Comment by lkolacz** [comment]
why this ticket is in 'ready' status since it's in develop branch from more then 2 weeks ..
