### ISSUE TITLE
ERP integrations improvements

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1300]
child of #1299

- [ ] When a UN agency user enters a CSO/PARTNER’s vendor number and implementing business area and selects ‘submit,’ the system displays the name of the CSO/PARTNER (as entered in the agency-specific ERP) and prompts the UN user to confirm or cancel the vendor number entered.

Use `/api/externals/partner-basic-info/?vendor_number=NUMBER&business_area=AREA` to get partner name

- [ ] Users will be restricted to only inputting information for CSO/PARTNERs that operate in their assigned country/countries.

For ease of implementation only allow to enter vendor number when agency user is toggled under partners country of origin.

**Comment by kenzo23312** [comment]
@maciej-jaworski  this endpoint returns: 

` "detail": "Your agency doesn't support basic partner info lookup."` 

What is correct data for this endpoint ?

**Comment by maciej-jaworski** [comment]
It works for UNIECF the way its supposed to, closing
