### ISSUE TITLE
Project list display name display issue

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1309]
Real life project names will be quite long, currently listing table doesn't display such cases properly
<img width="338" alt="screen shot 2018-08-27 at 11 55 39" src="https://user-images.githubusercontent.com/1492815/44653900-4f26fb00-a9f0-11e8-884a-bf62c35d7443.png">

Rearranged fakedata to generate longer names

**Comment by kenzo23312** [comment]
@brandinalexander to clarify with UNICEF which columns we should persist and which not

**Comment by maciej-jaworski** [comment]
Wasn't this discussed already?
IIRC they wanted to keep all the columns just make the table wider and horizontally scrollable.
