### ISSUE TITLE
CFEI filters focal point

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1446]
https://trello.com/c/qc0fewj7/141-cfei-filters

**Comment by maciej-jaworski** [comment]
This is a frontend issue, request url from frontend is 
`/api/projects/open/?agency=1&focal_points[]=369&focal_points[]=370&page=1&page_size=10`

While it should be 

`/api/projects/open/?agency=1&focal_points=369,370&page=1&page_size=10`
