### ISSUE TITLE
CFEI - HQ Editor permissions

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1505]
https://trello.com/c/d3oVg4eD/222-cfei-finalization-hq-editor

- [ ]  1. User cannot view the recommended partner nor the shortlisted ones
- [x] 2. the send for decision button is present and activated (this should not be on the screen)
- [ ] 3. User cannot view the review summary
- [ ] 4. Error message received that permission denied

**Comment by maciej-jaworski** [comment]
The expected results differ from spec passed, moved the trello card back to requires discussion.

**Comment by maciej-jaworski** [comment]
![image](https://user-images.githubusercontent.com/1492815/48199745-5d34b880-e35d-11e8-834b-1dd47f317950.png)
New permission around finalized CFEI
