### ISSUE TITLE
Project Detail Application API 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#154]
**Overview**
We currently don't have any easy for the frontend to tell if an application has been submitted to a project easily. See the following screen https://invis.io/32CLE7585#/242436062_EIO-Partner-Application_02

**Possible Solutions**
- Frontend just calls /applications?eoi_id=123 (Just reuse existing endpoint)
- For partner users, we return the application id as part of eoi/project detail response (if it exists). The frontend can just call /applications/:id/ when navigating to that tab.

**Comment by lkolacz** [comment]
endpoint to get information about submitted application is 
`http://localhost:8080/api/projects/{project-id}/partner-application/`
on branch name: `feature/#154-Project-Application-CN`
Logged partner member will see does the partner organization submit application .. If this endpoint return 404 that is meaning that "partner" doesn't submit any application for this project.. If field 'cn' is null that mean that Application doesn't contain content note
