### ISSUE TITLE
Partner Profile - Country Profile Inherit Field Logic

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#157]
**Overview**
See following spec: https://docs.google.com/spreadsheets/d/1dpBECNT5eMwMB5PkV0SlaxULV7IlnACRyRM0IiI7bh0/edit#gid=0

Fields that are specified as "Sync and Lock" should be inherited from the HQ and be non-editable

**Comment by lkolacz** [comment]
front-end part needed here to check changes with name section in some places:
org_head -> head_of_organization
budgets -> origin_budgets

**Comment by elyk** [comment]
cc @kenzo23312 to change the fields above
