### ISSUE TITLE
Partner Detail Summary Endpoint 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#180]
**Overview**
Need profile summary endpoint that doesn't return all profile detail

**Comment by marcindo** [comment]
We have one for comparison screen, still missing for application summary and verification modal views

**Comment by marcindo** [comment]
Separate endpoint for application summary: 
https://projects.invisionapp.com/share/9VCMWHXJS#/screens/246070584

Also including update from this trello issue?  @brandinalexander @lkolacz  
https://trello.com/c/OD4nJOl8/87-cfei-review-cn
