### ISSUE TITLE
Filter Partners Endpoint

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#196]
- By countries (should accept multiple)
- By not HQ

Needed more as a priority for this: https://projects.invisionapp.com/share/9VCMWHXJS#/screens/244894753

**Comment by marcindo** [comment]
@lkolacz I believe we need filtering so we can only display partners who operate in project's countries. Should be done in partners/short endpoint

**Comment by kenzo23312** [comment]
Filters when picking partners CFEI invitation or DS selection.

Clarify:
Should we filter out partners which do not operate in countries specified in project?
