### ISSUE TITLE
Add country to /api/partners/short

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#199]
This endpoint should also have country name or support filtering by country

**Comment by lkolacz** [comment]
Support filtering by country was done at 13th of November.
Need to add only `country_code`.

**Comment by lkolacz** [comment]
DONE

**Comment by lkolacz** [comment]
Marcin nead enhancement:
```
Could you also add 'limit' parameter to this endpoint?. Also it would be helpful to have filtering by list of country codes here
```
