### ISSUE TITLE
Profile Detail View

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#20]
The view-only (non-edit) view of the partner profile. 

Corresponding Invision link:
https://invis.io/32CLE7585#/247140206_Organization_Profile_01

- Each section should be collapsable
- Pencil icon on each should bring the user to the edit section of the corresponding page (being built here: https://github.com/unicef/un-partner-portal/issues/15)
- Edit button on the top should bring the user to the first section in edit (Identification)

**Comment by kasialanecka** [comment]
@elyk Brandon pointed out that the link in this ticket is not correct and spoke with me about that. I believe that the right one is: https://invis.io/32CLE7585#/247140206_Organization_Profile_01

**Comment by elyk** [comment]
Ok updated. Thanks.
