### ISSUE TITLE
Partner Profile Locked/Pending State 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#215]
**Overview**
Need to have a locked/pending state for the partner profile.. this is when:
- Deactivated
- Sanctions list check comes up
- More to be added

**Comment by kenzo23312** [comment]
On wireframes we have only deactivation:

https://projects.invisionapp.com/share/9VCMWHXJS#/screens/249613326

We do not have any specific information beside that how it should work - need clarification. 

In docs it's mentioned about: 
Just ability to deactivate profile without details.
