### ISSUE TITLE
Complete/Close Project/CFEI API  

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#216]
**Overview**
Need to expose ability to Complete a CFEI with a reason. 

**Relevant Wireframes/Screens**
https://invis.io/9VCMWHXJS#/246594985_Agency_-_EIO_01_CFEOI_Open_Details_01-Close-Modal

**Comment by lkolacz** [comment]
it's already done! url project:eoi-detail -> patch method post:
```
{
            "justification": "text",
            "completed_reason": COMPLETED_REASON.canceled
}
```
