### ISSUE TITLE
Delete concept note

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#220]
We need endpoint for deleting submitted concept note

https://projects.invisionapp.com/share/32CLE7585#/screens/242442247

**Comment by lkolacz** [comment]
backend is done ... 
@kenzo23312 .. please make FE part as well. Thx :)

**Comment by kenzo23312** [comment]
Field 'cn' is not cleared despite DELETE request return 204.

**Comment by lkolacz** [comment]
@kenzo23312 
Every thing is working fine...
Are You sure You use delete method on endpoint `http://localhost:8080/api/projects/{app_id}/partner-applications-delete/`
