### ISSUE TITLE
Change First, Last -> Full Name 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#226]
Anywhere we have first and last name, we need to change this to one line/field - full name. 

This includes:
- Current User
- Head of organizations
- Board of Directors
- Authorized officers

This needs to be changed on registration, org profile, and anywhere else exposed.

**Comment by lkolacz** [comment]
backend part is done !

**Comment by lkolacz** [comment]
common branch name `bugfix/#226-fullname`

**Comment by marcindo** [comment]
frontend part is done, but some backend regression is blocking testing
