### ISSUE TITLE
Per View Permissions

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#263]
Need to add permissions to ensure partners, agencies and their roles within each are restricted accordingly for the following views (will add more over time):

- `/api/projects/application/id/` 
- `/api/projects/application/open/`  (ensure access to Partner-ID being sent)
- `/api/projects/application/direct/`  (ensure access to Partner-ID being sent)
- `/api/projects/application/unsolicited/` (ensure access to Partner-ID being sent)

**Comment by elyk** [comment]
@lkolacz please add in any here so we can keep track of.

**Comment by lkolacz** [comment]
endpoints:
```
/api/projects/applications/open/
/api/projects/applications/direct/
/api/projects/applications/unsolicited/
```
already ensure access to Partner-ID being sent

**Comment by lkolacz** [comment]
@elyk  
`/api/projects/unsolicited/` - add Agency members only
to convert to ds Frontend should verify is agency member equal to unsolicited agency ... because UNICEF shouldn't convert unsolicited CM that were sent to for example WFP

**Comment by lkolacz** [comment]
@elyk 
`/api/projects/application/pk/convert-unsolicited/`
only agency owner and at least editor is allowed to convert

**Comment by lkolacz** [comment]
create and add permission  class IsApplicationFeedbackPerm to ApplicationFeedbackListCreateAPIView endpoint

**Comment by lkolacz** [comment]
AwardedPartnersListAPIView endpoint with extra permission - IsAgency

**Comment by lkolacz** [comment]
EOIReviewersAssessmentsListAPIView only for agency member with role editor
