### ISSUE TITLE
Partner profile details fix

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#265]
- [x] `working_languages_other` should be text field as in documentation.
- [x] `working_languages` choices should be WORKING_LAGNUAGES_CHOICES now it's list of countries
- [x] in class Partner `country_presence` should be list of countries 
- [x] `directors`, `authorised_officers` and all of other arrays with objects fields needs to add delete logic - now only add works
- [x] PATCH for `/api/partners/1/mandate-mission/` returns error -> 'ManyRelatedManager' object is not iterable
- [x] Field `collaborations_partnership_others` in collaboration is not needed anymore
- [x] Collaboration field `collaboration_evidences` not saving objects after PATCH - please check / fix
- [x] PATCH for files in `project-implementation` return error
 {"report":["The submitted data was not a file. Check the encoding type on the form."]}
- [x] Project Implementation - Audit field with link to org website is doubled name - `link_report` please rename to `link_org_website` form won't work with same names of fields.
- [x] Project Implementation validation of link fields - url has to start with `http://` any other link won't be PATCHED as we got error invalid url - it's not user friendly. 
- [x] Other info field `org_logo` returns for file -> "CommonFile <pk:47>" after patching
- [x] Other info field `other_documents` is those common files? It has different structure than Common File please make it consistent with Common File structure {id, file_field}
- [x] Field `location_field_offices` returns array of ids [1,2] not objects 
- [x] Field `collaboration_evidences` return for uploaded file -> Cannot assign "37": "PartnerCollaborationEvidence.evidence_file" must be a "CommonFile" instance.
- [x] Fields `other_doc` 1 - 3 returns ID instead of url
- [x] new created country profile does not fill three default fiscal years in `funding` section
- [x] array fields like `authorised_officers` shouldn't be deleted/cleared while not sending this field in payload through PATCH

**Comment by elyk** [comment]
@kenzo23312 changing the audit link report to `audit_link_report`

**Comment by elyk** [comment]
@kenzo23312 other_documents is now no longer. We now have:

`other_doc_1`
`other_doc_2`
`other_doc_3`

These all act same as CommonFile (accept id on create and return url on read)

**Comment by elyk** [comment]
@kenzo23312 if you end needing the common file ids to post back (if they're already created), @lkolacz can just comment out the following in CommonFileSerializer:

```
    def to_representation(self, obj):
        rep = super(CommonFileSerializer, self).to_representation(obj)
        return rep['file_field']
```

You'll then get the id and url back on read as a dictionary.

**Comment by lkolacz** [comment]
DONE:
```
directors, authorised_officers and all of other arrays with objects fields needs to add delete logic - now only add works
```
on branch name: `feature/#156-partner-profile-update`

**Comment by lkolacz** [comment]
latest improvements on branch `bugfix/#265-partner-profile-details-fix`
