### ISSUE TITLE
Modifications to /accounts/me/ / current partner toggle 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#289]
Backend
- [ ] Return legal_name for all country profiles (we are sending it, just not created at profile creation)
- [x] Return is_hq for those that are hq (this should be at the root level) 
- [x] Return partner org logo 
- [x] Return the type of organization
- [] Return Agency org logo

Frontend 
- [x] Refresh current view after changing current partner
- [ ] Display partner org logo

**Comment by marcindo** [comment]
Moving to in progress as at least logo display is not done yet

**Comment by marcindo** [comment]
it's done in 417 but needs testing with real images, also logo for agency should be added as well
