### ISSUE TITLE
Agency Open CFEI - Results View + API Integration

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#293]
**Overview**
We need to build out the view + integrate the API (being completed in this ticket: https://github.com/unicef/un-partner-portal/issues/291) for the results tab of a CFEI. 
This includes:
- Review Summary section (adding review summary + uploading file)
- Awarded Partners section (withdraw award behavior + download CN behavior)
- Reviewers section (send reminder link if not all assessments are completed)

**Relevant Wireframe**
https://projects.invisionapp.com/share/9VCMWHXJS#/screens/245638540_Agency_-_EIO_01_CFEOI_Closed_Results_05

**Comment by marcindo** [comment]
Still missing parts of BE:
- cn added to awarded partners respnse
- way to push notification to reviewer
