### ISSUE TITLE
Notifications API endpoint 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#294]
**Overview**
See wireframe added below. We need the following endpoints: 

- /api/notifications/
- /api/notifications/:id/

We need to support the ability to:
- Fetch/GET all notifications or just one notification
- Mark one or all as unread (perhaps a delete request to /api/notifications/)

This will be for the current logged in user. 

**Relevant Wireframe**
https://projects.invisionapp.com/share/9VCMWHXJS#/screens/248642963

**Comment by lkolacz** [comment]
@elyk I understand that you mean mark as read (because that what it is in mockup) .. not unread
`Mark one or all as unread (perhaps a delete request to /api/notifications/)`

**Comment by elyk** [comment]
@lkolacz yes, sorry. Mark all as read.
