### ISSUE TITLE
Non INGO - Profile Logic

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#322]
Here are our Partner types:

```
    ('CBO', 'cbo', 'Community Based Organization (CBO) '),
    ('NGO', 'national', 'National NGO'),
    ('Int', 'international', 'International NGO (INGO)'),
    ('Aca', 'academic', 'Academic Institution'),
    ('RCC', 'red_cross', 'Red Cross/Red Crescent Movement'),
```

For all types besides `Int`, we need to treat them as country profiles. Meaning, when they click on the organization profile section, we go directly to the partner profile. 

These should also be treated the exact same as country profiles for the fields that get filled out, except identification -> basic information needs to remain locked.

**Comment by kenzo23312** [comment]
for all of others than Int types is_hq = false ?

**Comment by elyk** [comment]
That field is irrelevant for all other types, so can ignore. I'm not sure what it returns now, but I can modify to make sure it returns `False` if you need it.

**Comment by kenzo23312** [comment]
yes please make it consistent with logic country profile / hq

**Comment by kenzo23312** [comment]
Unlock identification tab for is_hq = false, display_type=INGO
