### ISSUE TITLE
Separate endpoints for partner profile summary

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#344]
This is from agency point of view: 
We need separate endpoints for different views of partner profile summary, returning only needed data
Comparison (ideally returns a list of partners from ids): https://projects.invisionapp.com/share/XYCP55TJQ#/screens/244899878
Application details: 
https://projects.invisionapp.com/share/XYCP55TJQ#/screens/245867419

**Comment by lkolacz** [comment]
we decided with Marcin that we will skip `Application details` because it is DONE.
