### ISSUE TITLE
Add endpoint for partner name and status

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#347]
Client wants to display verification icon and flags next to the partner name pretty much everywhere, so we need endpoint to quickly fetch those few flags along with partner legal_name by id
Example on this mock in header section: 
https://projects.invisionapp.com/share/XYCP55TJQ#/screens/249613372

**Comment by elyk** [comment]
@marcindo I'm not sure why we need an endpoint? I think everywhere we just return partner it should be an object containing this information.

**Comment by elyk** [comment]
We will return a new field everywhere there is partner as `partner_details`as the partner object.  We will leave current fields (partner id, partner name) as is.

**Comment by lkolacz** [comment]
I decided to have name `partner_statuses` because details are pretty everywhere ... and this name have more sense IMO.
cc @elyk OK?

**Comment by elyk** [comment]
@lkolacz ok sounds good. Saw this comment after CR.
