### ISSUE TITLE
Projects List/Create API

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#35]
See doc here: https://docs.google.com/document/d/1e7H1yjrFwrORpD1i6Ythili649-8ACuqmJh-B4XUgwY/edit#heading=h.9q4mrjb3jesp

Projects API for:
- open  (/open/)
- direct (/direct/)
- pins (/pins/)

The above should include:
- GET (plus filtering/sorting) 
- POST 

This API will be the views for:

Open
-------
https://invis.io/32CLE7585#/242435123_EIO_Overview
https://invis.io/9VCMWHXJS#/244894751_Agency_-_EIO_01_CFEOI

Direct
-------
https://invis.io/9VCMWHXJS#/244894754_Agency_-_EIO_02_DS

Pins
----
https://invis.io/32CLE7585#/242435130_EIO_Starred

**Comment by lkolacz** [comment]
@elyk -> links are not working for me .. access denied :((( 
(only those with 'share' in URI are working for me .. 
like: 
https://projects.invisionapp.com/share/T4CGYCOAP#/screens/242435613_Registration_01

**Comment by elyk** [comment]
@lkolacz updated
