### ISSUE TITLE
Filter for unsolicited concept note

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#370]
`project_title` filter in unsolicited concept notes is not working

Leszek explenation:
we have there JSON field .. we have to put whole title instead of few chars ... JSON Field support only `contains` (`icontains` like we have every where is not supported by JSON FIeld .. we can change to have every where `contains` or live with this..) (... we can also have elasticsearch... but that will make things more complicated .... but possible)
Adam was talking about `ApplicationsUnsolicitedFilter` filter.

**Comment by lkolacz** [comment]
it's already done - in develop
