### ISSUE TITLE
Agency -> Partner Applications List API Integration + UI 

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#382]
Applications partner list api integration + UI

View:
https://projects.invisionapp.com/share/9VCMWHXJS#/screens/247079567

Endpoint:
/api/projects/applications/ (returns all applications, regardless of type or partner). 

Will need to pass in partner id (partner=1) for whichever is being viewed. 

For showing only those awarded can pass in did_win=True

Depends on this PR: https://github.com/unicef/un-partner-portal/pull/389

Note - that doesn't contain the filters for the type. Will need to wrap back to.

**Comment by elyk** [comment]
Another ticket / work done on this: https://github.com/unicef/un-partner-portal/issues/384 for API. Repurposing for frontend/api integration.
