### ISSUE TITLE
Partner API Detail

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#39]
Endpoint:
/partners/:partnerID/

Corresponds to the following screens:
https://invis.io/32CLE7585#/247138611_Organization_Profile_00_Copy_3
https://invis.io/32CLE7585#/247140206_Organization_Profile_01
https://invis.io/9VCMWHXJS#/244900467_Agency_-_Partners_02_Hq-Profile

**Comment by lkolacz** [comment]
@elyk I don't have a permission for those links :(

**Comment by elyk** [comment]
Updated links.

**Comment by lkolacz** [comment]
branch name: `feature/#39-partner-API-Detail`
GET /api/partners/1/org-profile

```
[
    {
        "id": 1,
        "legal_name": "legal name 0",
        "country_code": "PL",
        "is_hq": true,
        "country_profiles": [
            {
                "id": 2,
                "legal_name": "legal name 1",
                "country_code": "DE"
            }
        ]
    }
]
```

**Comment by lkolacz** [comment]
we need update on front end side on registration process ... fields are now defined in different way
```
-                "org_head_first_name": "Jack",
-                "org_head_last_name": "Sparrow",
-                "org_head_email": "captain@blackpearl.org",
+            },
+            "partner_head_organization": {
+                "first_name": "Jack",
+                "last_name": "Sparrow",
+                "email": "captain@blackpearl.org",
             },
```
we need improvements on it by Marcin, Thx
