### ISSUE TITLE
Partner View - Application Statuses

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#407]
Partners application list for Open CFEI(https://www.evernote.com/l/AKK2rBVXTWZDn4LKECE4bZonf2EJ3CBAs4Y). They need to be changed to the following:

- Application Under Review - If application isn't did_win=True and EOI is still open (not completed) 
- Application Unsuccessful - If application isn't did_win=True and EOI is closed (completed)
- Application Successful - If application is did_win=True, but didn't accept or decline
- Selection Accepted - If application is did_win=True and did accept
- Selection Declined - If application is did_win=True and declined
- Selection Retracted - If application is did_win=True but did_withdraw

**Comment by elyk** [comment]
cc @kenzo23312

**Comment by lkolacz** [comment]
@elyk We were together with Marcin think about what do You mean .. and have no Idea what to do in this area... please bring more clean information what shall we do here. Thx!

**Comment by lkolacz** [comment]
I'm moving this ticket to backlog because it's nor ready to work on it.

**Comment by lkolacz** [comment]
@elyk We got Your point now... You want to replace statuses column with that will show them.... OK

**Comment by elyk** [comment]
@lkolacz correct. This is ONLY for **partner** view. Please keep statuses same as they are for Agency.

**Comment by lkolacz** [comment]
@kenzo23312 it is under `application_status` field

**Comment by marcindo** [comment]
added change for applications table to the PR
