### ISSUE TITLE
Clicking on date in datepicker causes date to decrement

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#411]
https://www.evernote.com/l/AKJdbaILev9ERrd-w029eUfoX4j-UcM1Zoo

STR:
- Pick a date
- Click on notification of results again
- Date decrements

We've run into this on other projects. It's some issue with native JS data object and wasn't replicable in PL timezone. 

The solution was to use momentjs

 `export const formatAsDateObject = (value) => moment(value).toDate()`

**Comment by marcindo** [comment]
done in #416
