### ISSUE TITLE
Separate endpoint with permission config returned for partner or agency

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#450]
Have a separate endpoint that returns config for views/actions that change depending on user permission. 

Partner will need to have Partner-ID sent in header

**Comment by lkolacz** [comment]
@brandinalexander ... this ticket is unclean for me :( .. too abstract :/

**Comment by marcindo** [comment]
I believe this comes from Kyle's idea to set permissions from backend response - with various fields, like 'can edit cfei', 'can verify partner' but we're already doing permissions in frontend based on some other informations, and implementing this style will be time-heavy

**Comment by kenzo23312** [comment]
this may be closed due to new ticket for user permissions.
