### ISSUE TITLE
Return Profile Completed Status in Each Section

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#456]
For each section below, we need to return a boolean `has_finished` which is a computed property based on if all of the information is filled out within that section of the profile. 

This is what the warning icons will read: https://www.evernote.com/l/AKKUB8RddZBEGr20qHUNOaHsdM5ca8ThpVY

These should all be on the Partner Profile serializer

- Identification
- Contact Information
- Mandate and Mission
- Funding
- Collaboration
- Project Implementation 
- Other Information

**Comment by elyk** [comment]
We will need to have an overall status which will restrict from submitting a CN.

**Comment by elyk** [comment]
@lkolacz can you take over the rest of the ticket? See I started a branch: https://github.com/unicef/un-partner-portal/tree/feature/%23456-completed-status-each-section

You can see under `PartnerProfile` I started creating a method for checking each section. What we still need to do is:
- Finish off adding all the sections (the last couple had TODOs)
- Add in a method that checks all of these (if every section is complete)
- Expose each in the PartnerProfile serializer, so @kenzo23312 can get access to all of them

**Comment by elyk** [comment]
@lkolacz I think for the BooleanField's for partner profile (or any related models), we will have to change to NullBooleanField, so we know if it has been filled out or not yet.

**Comment by lkolacz** [comment]
@elyk I think I did it. Please take a look on code review.

**Comment by lkolacz** [comment]
@kenzo23312 new field on each partner profile section `has_finished` .. please implement it on FE!

**Comment by lkolacz** [comment]
@kenzo23312 You have everything right now in develop .. if You are working on Your own branch just merge it ;-)
If You need anything, just ping me ;-)

**Comment by elyk** [comment]
@kenzo23312 I am moving this back to delivered until the missing fields are identified and coordinated with @lkolacz on.  

@brandinalexander FYI this pertains to:
https://trello.com/c/FQXipD50/7-profile-completion
https://trello.com/c/ereZx2Wq/64-profile
https://trello.com/c/atAnB5DK/57-profile-tabs

**Comment by lkolacz** [comment]
this 3 trello cards was done under #581 issue
