### ISSUE TITLE
Handle for case where no weight was entered, but project has weighting

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#457]

**Comment by lkolacz** [comment]
@marcindo @kenzo23312 
backend part is done in branch name `bugfix/#457-no-weight-situation`

I'm returning 2 extra validation errors in case when we select has_weight and not bring weight in assessment criteria ... and if has_weight is unselected and we define weight.
Endpoint: (eoi-detail) /api/projects/{id}/
