### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#462]
http://localhost:8080/api/projects/applications/unsolicited/?page=1&page_size=10&project_title=now

Field project_title is not filtering correctly

**Comment by elyk** [comment]
@kenzo23312 duplicate of https://github.com/unicef/un-partner-portal/issues/465?

**Comment by lkolacz** [comment]
all filtering ('icontains' )project title are done... I go throw all title fields and check
