### ISSUE TITLE
Creating new UCN

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#463]
After creating new UCN:
Response return "Agency: UNICEF <pk:1>" as agency 
Not adding country, title, locations, specializations to object 

Payload:
{"countries":[{"country":"AU","locations":[{"admin_level_1":{"name":"Western Australia","country_code":"AU"},"lat":"-23.57909","lon":"122.34375"},{"admin_level_1":{"name":"Queensland","country_code":"AU"},"lat":"-28.31889","lon":"147.30469"},{"admin_level_1":{"name":"South Australia","country_code":"AU"},"lat":"-27.07380","lon":"129.37500"}]}],"specializations":[1,49,41],"agency":1,"title":"Test","cn":454,"country_code":["AU"],"locations":[{"admin_level_1":{"name":"Western Australia","country_code":"AU"},"lat":"-23.57909","lon":"122.34375"},{"admin_level_1":{"name":"Queensland","country_code":"AU"},"lat":"-28.31889","lon":"147.30469"},{"admin_level_1":{"name":"South Australia","country_code":"AU"},"lat":"-27.07380","lon":"129.37500"}]}

**Comment by elyk** [comment]
@kenzo23312 this should be fixed now on separate branch . I'm not sure why we are passing in countries explicitly, but we don't need to. Just locations as we normally do. 

PR here: https://github.com/unicef/un-partner-portal/pull/482
