### ISSUE TITLE
CFEI Ordering / Filtering 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#47]
Thinking through different users and how they’d want to see this table ordered/filtered.

- Partner — I’m probably most interested in seeing those that are open (where deadline hasn’t passed). I don’t care as much about those that are closed/under review. If I applied, I’d see under my applications. If I didn’t, oh well, I missed it.
- Agency - I care most about the ones under review and open (for those my agency created of course)
- Outside / Non Registered - Probably cares most about the ones that are upcoming / still open.

Proposed doc: https://docs.google.com/spreadsheets/d/1zIjLAzsn0juD4Vq7So_PbzsJLlc6VCFTFHCnzui3Pqg/edit#gid=0

Open questions:
- Do partners and non registered users need to see/access past CFEI's that they weren't a part of 
- Do we need to filter by agency office for agency view or is country + agency enough

**Comment by elyk** [comment]
Need to remove any completed to not show in cfei list for partner

**Comment by lkolacz** [comment]
It's already done by Kyle
