### ISSUE TITLE
Map Component Consistencies

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#476]
We need to keep the same behavior where our map components are used (new Project and Profile). 

- Remove displaying labels (https://www.evernote.com/l/AKIhjDZ5ufRJ9bwa8TaI1OyZ03Ej3p2j-WM). These should just display on the map marker on select 
- Place names should auto suggest as you're typing them in (currently on profile)

Comes from: https://trello.com/c/aBwwmjMT/19-mapping-feature

**Comment by marcindo** [comment]
Done in #560
