### ISSUE TITLE
If CFEI is > Deadline status should be "Closed / Under Review"

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#479]
https://www.evernote.com/l/AKLt-yfsmMhNO7nu7sJRs1UBMILk-Xtblvg

See Desired: 

https://invis.io/9VCMWHXJS#/246028124_Agency_-_EIO_01_CFEOI-Hover

@lkolacz I think the best approach to solve this is:
1. Create an `is_completed` field on `EOI`
2. Status becomes computed:
- Open if `is_completed` is False and < deadline_date
- Closed / Under review is `is_completed` is False and > deadline_date
- Completed if completed is True

Adding @marcindo since we will then require change to how completed is sent (will then be a boolean)

**Comment by lkolacz** [comment]
@elyk 
```
    @property
    def is_completed(self):
        return self.completed_reason is not None
```
`is completed` already on place...
will update/change status
