### ISSUE TITLE
Weight Adjustments

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#488]
Need to further adjust weights:

- The sum of all weight criteria must be equal to 100. This will be up to the user to do and we will just  invalidate the creation if it's not 100. (backend + frontend)
- For each weight value (at time of assessment), the maximum score is equal to the value entered for the weights (backend + frontend)
- We need to expose the weights in the selection criteria (see https://trello.com/c/hgqaW7kg/36-cfei-weighting-of-selection-criteria) (frontend)

**Comment by elyk** [comment]
cc @marcindo updated description after discussion with client

**Comment by marcindo** [comment]
ad 2 this very time heavy due to unexpected issues with redux-form library, but I think I found one possible solution, still will take plenty of time
ad 3 where weights should be displayed? only on selection criteria list in cfei overview?

**Comment by elyk** [comment]
They should be displayed on the selection criteria list in cfei overview and when the user is actually entering the assessment score. For example: 
- ___ / 25
- ___ / 75

**Comment by elyk** [comment]
@lkolacz can you take on the rest of this task? I started a branch here: https://github.com/unicef/un-partner-portal/tree/feature/%23488-weight-adjustments that made adjustment for calculating weights. 

We also need to add backend validation so that:
- Sum of all weights when creating an EOI == 100 (if eoi uses weights)
- Each value is not greater than weight criteria when assessment is being entered

**Comment by marcindo** [comment]
But do we want sum of weights === 100 or just <== 100, on frontend latter is currently implemented

**Comment by lkolacz** [comment]
@marcindo Sum of all weights have to be equal to 100 so it will be `===` ;-)

**Comment by lkolacz** [comment]
Backend part (as Kyle mention in comment above) is DONE

**Comment by marcindo** [comment]
Fixed on Frontend, so everything is done
