### ISSUE TITLE
Type change

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#494]
Replace CSO-Initiated with "Unsolicited Concept Note"

https://projects.invisionapp.com/d/main#/console/11566713/244894754/comments/87886450

Change DS source:
CSO-Initiated should be "Unsolicited Concept Note"

**Comment by lkolacz** [comment]
@kenzo23312 I don't have permission to this.

**Comment by kenzo23312** [comment]
@lkolacz https://invis.io/9VCMWHXJS#/244894754_Agency_-_EIO_02_DS

**Comment by lkolacz** [comment]
DONE
