### ISSUE TITLE
Replace complete with finalize

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#495]
https://projects.invisionapp.com/d/main#/console/11566713/246594985/comments/87946403

In consts.py

Completed reasons need to change to:

- Finalized - Partner accepted
- Finalized - CFEI canceled
- Finalized - No successful applicant

**Comment by lkolacz** [comment]
@kenzo23312 I don't have permission to this.

**Comment by kenzo23312** [comment]
@lkolacz https://invis.io/9VCMWHXJS#/246594985_Agency_-_EIO_01_CFEOI_Open_Details_01-Close-Modal
