### ISSUE TITLE
Profile Details - Contact Information Missing for Authorized Officers

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#499]
See desired: https://invis.io/32CLE7585#/244226740_Organization_Profile_03

Currently missing Telephone, Fax, Email fields on each Authorized Officer. 

Comes from: https://trello.com/c/qp4ElZhU/29-hq-profile-contact-info-tab

**Comment by kenzo23312** [comment]
@lkolacz  can we check if 'directors' has those fields -> Telephone, Fax, Email ?

**Comment by elyk** [comment]
@kenzo23312 it's only for authorized officers who need them

**Comment by kenzo23312** [comment]
Ok so it's done
