### ISSUE TITLE
Head of Organization Email Not Filled In 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#500]
When filling in the head of organization's email on registration, it's not populating in the profile. 

Comes from: https://trello.com/c/iXOT4513/30-hq-profile-contact-info-tab

**Comment by kenzo23312** [comment]
Can we check this issue on bakcend side ? @lkolacz

**Comment by elyk** [comment]
@kenzo23312 this is a frontend issue. We're not sending the email:

https://www.evernote.com/l/AKLCwcxJFuxAVLXjC-DqGuT7VYVg1OCo2wQ

It was added while filling out the profile
