### ISSUE TITLE
Org Profile: Fields titled "Optional" should not be required

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#501]
If a field is optional, it should not show up as red if not filled out. 

Additionally, it shouldn't show up as the red "missing indicator", but that will be handled in ssues/456

**Comment by kenzo23312** [comment]
In backend under mailing_address
Mailing_address:
{org_email: ["This field may not be blank."]}

In wireframe this is optional we need to change validation on server.

**Comment by kenzo23312** [comment]
Also this field in backend should be optional returning error when empty: 
{"info_to_share":["This field may not be blank."]}

**Comment by elyk** [comment]
@kenzo23312 these should now be updated

**Comment by kenzo23312** [comment]
info_to_shre field is still required

**Comment by elyk** [comment]
Updated `info_to_share`

**Comment by elyk** [comment]
Now finally fixed. Sorry for back/forth.
