### ISSUE TITLE
Default Status not set properly - Direct Selection

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#509]
As an agency user, if you toggle to Direct Selection tab, `Active` is visually shown, but not sent to the server unless you hit "Search"

Similar issues still occurring here: https://github.com/unicef/un-partner-portal/issues/455

**Comment by kenzo23312** [comment]
I have double checked this and it's working, maybe we can check this together?

**Comment by elyk** [comment]
Direct Selection: http://recordit.co/DuJldpnLKv
Open Selection: http://recordit.co/fx5LdbThWq

**Comment by elyk** [comment]
Still facing this when navigating through tabs:

http://recordit.co/A9OiV4R72X
