### ISSUE TITLE
In Specialization Filter Dropdown, group by Sector

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#510]
We need to show each area of specialization, grouped by Sector. 

Comes from: https://trello.com/c/Ik1ERCXg/42-imagepng

**Comment by elyk** [comment]
@marcindo - can we add on Partner view as well? 

Also, what is level of effort for multi-select?

**Comment by marcindo** [comment]
I believe it's 0 effort to make it multiselect, but is backend accepting list of specializations? My simple test failed

**Comment by elyk** [comment]
If 0 effort, let's please do. I will modify backend to accept a comma separated list of specialization ids

**Comment by marcindo** [comment]
I'm not sure though how hard it will be to change all filters to send comma separated list, @kenzo23312 ?

**Comment by marcindo** [comment]
frontend part is done
