### ISSUE TITLE
Dashboard Applications - Pending Offers not linked correctly

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#512]
In the partner dashboard, the applications in "Pending Offers" look to be using the application id and not the cfei application id.

Comes from: https://trello.com/c/m7nCFPis/46-imagepng

**Comment by marcindo** [comment]
I'm only receiving cn_id so yes, application id in that endpoint. Fix must happen on BE (add eoi.id)

**Comment by marcindo** [comment]
I've noticed issues with link, so pushed some changes to bugfix/#512-dashboard-application-links it still observers cn_id field so extra change will be needed if it's changed to eoi_id

**Comment by elyk** [comment]
@marcindo exposed `eoi_id` on your bugfix branch
