### ISSUE TITLE
Should entire row be selectable? 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#518]
On Applications List and Preselected list, I think the entire row should be selectable: 

https://www.evernote.com/l/AKKPh5zimVJDSboQochiLrUegVdfshn6g-E

We shouldn't make the user click the id to access application details. Surface area is too small.

**Comment by marcindo** [comment]
We updated grid library which includes change that should allow this to happen, need to check it though. We would also need to block events when user clicks on the icons to change app status

**Comment by marcindo** [comment]
I've added possibility to click entire row if proper props are passed to table component, and already implemented it on applications list. Do we need it anywhere else?
