### ISSUE TITLE
Direct Selection Issues

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#524]
- [ ] Invited partners not being saved properly: https://www.evernote.com/l/AKJRe_IPvABLBKwe4gGCLbk1hwGO0L8Bd8Q
- [x] Showing incorrect dates on details (it should be estimated start date and estimated end date): https://www.evernote.com/l/AKJRe_IPvABLBKwe4gGCLbk1hwGO0L8Bd8Q
- [ ] Goals, Objective, Expected Outcome should not appear as it's not part of creation 
- [x] Selected partner not showing up in the list view
- [ ] Issue by showing id (https://www.evernote.com/l/AKK193_WbrFDZoHoV2nSF0syKzufCkkM4PQ). This is backend change

Ticket here also reported by Unicef: https://trello.com/c/RTxEZncp/50-imagepng

Issues are for regular DS creation or UCN conversion.

**Comment by marcindo** [comment]
ad. 1 this is because BE is giving us invited partners not selected ones (invited partners exists only for open selection)  which is incorrect in the first place
ad. 3 There is no difference between api/projects/:id response for normal DS and converted DS, impossible to do

**Comment by elyk** [comment]
_ad. 1 this is because BE is giving us invited partners not selected ones (invited partners exists only for open selection) which is incorrect in the first place_ - @marcindo what is the payload sent over? We're expecting `applications`

**Comment by elyk** [comment]
To clarify, "Invited Partners" is selected partners here. 

We have these returned in the API: 
https://www.evernote.com/l/AKKlOJLyLCdKo4b6XB5J2zCYBRnpjNBuBMc

**Comment by marcindo** [comment]
what is the payload sent over? We're expecting applications I don't think it matters, it's just that on DS list view BE is exposing wrong field.  (on details view I see that partner who initiated converted UCN is added to selected partners

**Comment by marcindo** [comment]
partially done in #554

**Comment by elyk** [comment]
Ok. Didn't realize you were referring to list view.
