### ISSUE TITLE
Permissions / Access Restrictions

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#530]
Making note of several permissions / restrictions we need to put in place below: 

**Partner**
- [x]  As a Partner User, I should not be able to submit an application if my profile is not complete. This depends on https://github.com/unicef/un-partner-portal/issues/456
- [x] As a HQ Partner User, I should not have the ability to submit an application if I am currently toggled under the HQ profile. 
- [x] As an HQ Partner User, I should not have the ability to create a country profile until my profile is complete. This depends on https://github.com/unicef/un-partner-portal/issues/456

**Focal Point**
- [x] As an Agency User - Focal Point/Creator(s), I/we should not be able to award an application if the profile has not been verified yet (is_verified)
- [x] As an Agency User - Focal Point/Creator(s), I/we should not be able to award an application if the profile contains a red flag 
- [x] As an Agency User - Focal Point/Creator(s), I/we should not be able to award an application in an open cfei if all assessments have not been added for the application
- [x] As an Agency User - Focal Point/Creator(s), I/we should only be able to edit a CFEI 
- [x] As an Agency User - Focal Point/Creator(s), I/we should be the only ones allowed to pre-select/reject an application 
- [x] As an Agency User, if an EOI is completed, I should no longer be able to edit any of the information on it. Meaning edit, invite partners, manage reviewers. I should no longer be able to award/retract or preselect/reject. We essentially are locking the EOI. 
- [x] As an Agency User - Focal Point/Creator(s), once a CFEI deadline is passed, I should only be able to add reviewers and add other focal points. I should not be allowed to invite other partners or change any dates.

**Comment by elyk** [comment]
I think comment got overwritten, but references the following stories: 
https://trello.com/c/QPtnL2LB/62-imagepng
https://trello.com/c/YsmpCOmP/51-cfei-award-select-button
https://trello.com/c/q0BfaqRK/23-cfei-assessment
https://trello.com/c/kTd5Q1hz/17-cfei-submit-cn
https://trello.com/c/QtwkjDX6/26-cfei-award-select
https://trello.com/c/yRd2Ozo0/39-cfei-edit-cfei

**Comment by elyk** [comment]
@marcindo @lkolacz please just refresh this screen before updating next. I think previous updates got overwritten on description

**Comment by lkolacz** [comment]
@elyk goring throw trello cards you mention above I add:
- [ ] Should not be able to reject a CN if assessment has begun

**Comment by lkolacz** [comment]
@elyk My part is done here :)

**Comment by marcindo** [comment]
@elyk Frontend is done too
