### ISSUE TITLE
Send dict with invited partners

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#538]
For cfei details: Invited partners are sent only as list of Ids, but should have dict with partner name and informed date 
Currently we map id with partner name, but it will break when autocomplete is up

**Comment by elyk** [comment]
@marcindo - you can/should still send as list of ids. You can get the list of partners from `/api/partners/`

Informed date can/should be set on backend

**Comment by marcindo** [comment]
I meant the other way around:  that cfei details response only contains ids which is not enough for  FE to display all needed information

**Comment by elyk** [comment]
You'll see partners returned as list of dicts now:

```
    "invited_partners": [
        {
            "id": 1,
            "legal_name": "legal name 0",
            "partner_additional": {
                "id": 1,
                "legal_name": "legal name 0",
                "flagging_status": {
                    "red": 2,
                    "yellow": 0
                },
                "is_verified": null,
                "has_finished": true
            }
        }
    ],
```
Note - we don't have informed date. This will have to wait.
