### ISSUE TITLE
Differ fields name

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#555]
Please differ field names in those two sections:

-mailing_address
-org_head 

There is bug telephone with matching telephone in mailing address is taken from org_head due to same name of field.

**Comment by kenzo23312** [comment]
Please also differ names for link_report in sections:

-audit 
-report

'link_report' both have same field name

**Comment by lkolacz** [comment]
it is done on branch name `feature/#555-differ-fields-name`
