### ISSUE TITLE
UNHCR DB Import / Migration Outline

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#56]
We have received a data dump from the UNHCR database. We need to do a bulk import of relevant data into UNPP database. 

Open items are:
- Determining what type of data we need to import/load from UNHCR  
- Understanding the UNHCR schema / mapping to UNPP

There were talks of just importing registered partners and sending out a link (via email) for them to activate their accounts (perhaps new password), but this needs to be confirmed.

**Comment by elyk** [comment]
Might make sense to migrate partners over in groups/batches vs. all at once.

**Comment by brandinalexander** [comment]
Future feature.**
