### ISSUE TITLE
Profile: Annual Reports

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#570]
1.) When the user indicates no to having an annual report, the options for uploading or providing the website should not show

https://trello.com/c/ck2R91px/69-profile-annual-reports

2.) If a user uploaded their annual report, they do not have to also provide a link to the report on the website. Either option is ok but both not required as shown in the screenshot
https://trello.com/c/8lT3Epdl/61-profile-annual-reports

**Comment by brandinalexander** [comment]
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65267051a67f29ddba7fe91528535f5f4eae440a0e15fcf8df39baa47e21d40854b088270a36d43703adbf881eba00ba288c4e86bfba8e4dc3fa70.png)

**Comment by kenzo23312** [comment]
we need to do 'link_report' optional in backend

**Comment by elyk** [comment]
@lkolacz to make `link_report` optional
