### ISSUE TITLE
Application Feedback Undefined id sent

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#571]
https://www.evernote.com/l/AKJf5Wye_uVFjoVp7-bRyG6A9XLjZ5nj8hc

From a partner, if you go to a specific eoi, the feedback endpoint fails:

http://unpp-stage.tivixlabs.com/api/projects/application/undefined/feedback/

**Comment by marcindo** [comment]
I see that it fails first but then second request is sent which succeeds. Must be an issue of sending request prematurely  before application id is set, I'll investigate but low priority in my opinion
