### ISSUE TITLE
Dashboard / Withdrawn / Etc. Filtering 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#572]
Solve issues pertaining to:
https://trello.com/c/I6y3pWdb/67-cfei-pending-offers
https://trello.com/c/q6NHAL99/52-cfei-award-select-and-retract

**Comment by lkolacz** [comment]
@marcindo @kenzo23312 
in the second card .. in second half of description .. there is:
```
When the CFEI was opened to the results page, the feedback for choosing and withdrawing not there as well as there is no audit trail of the award and retraction.
```
Do You guys have any information about it.. should they be presented on app details or something ???
Could You share Your thoughts?

**Comment by marcindo** [comment]
I have no idea about audit trail, wasn't present in the mocks
