### ISSUE TITLE
Retracting Award

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#573]
We do not need to send `did_win=False` when the award is retracted. Want to keep record they were awarded, but retracted. 

https://www.evernote.com/l/AKK5TV9gSOlF7obAkfhmCi_kuRGvN4iYs78

If `did_withdraw=True` the button "Retract" needs to change to label "Retracted" and not be editable. 

Not sure if it's a local data issue, but application id isn't there (undefined) when sending to server, **so nothing works:** 
https://www.evernote.com/l/AKJk1Np8EGdNj5H0XKkKwrGFTZllounjL_U

**Comment by marcindo** [comment]
Might be regression because `http://localhost:8080/api/projects/:id/applications/awarded-partners/` doesn't contain application_id anymore,. I will also need to contain did_withdraw t o disable button

**Comment by marcindo** [comment]
Branch with frontend change needed for disabling is  bugfix/#573-retracting-award
