### ISSUE TITLE
Non-Confirmed User Application State 

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#59]
#After the user registers, what should they be able to do w/o confirming email?

We need a sticky banner to display at the top of the screen and persist on every screen. 

During this state, the user will not be able to perform any sort of write action.

**Comment by elyk** [comment]
@kasialanecka just one example on a screen of this should suffice.

**Comment by kasialanecka** [comment]
@elyk @kasfaw do we want to provide an option to click "ok" or sth so the user will be able to close this banner? Another option - maybe every time user lands on any subpage we can display modal with this information and he will have to click "ok" to close it and have access to the page content (which is annoying, but may cause quicker email verification?).

**Comment by kasialanecka** [comment]
Proposition: https://invis.io/32CLE7585#/251856981_EIO_Overview_Copy_2

**Comment by kasialanecka** [comment]
Second proposition: https://invis.io/32CLE7585#/252037671_EIO_Overview_Banner_Alternative

**Comment by elyk** [comment]
Per Ev's feedback, we will be going with the second proposition.
