### ISSUE TITLE
Predefined fiscal years

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#595]
After creating country presence profile in tab Funding - Budget there are no predefined 3 last fiscal years.

**Comment by lkolacz** [comment]
dupicate / dependacy of #157

**Comment by lkolacz** [comment]
@kenzo23312 if country profile fields `hq_budget` & `hq_org_head` are filled with the right data

**Comment by lkolacz** [comment]
backend part is done
