### ISSUE TITLE
Sharing menus between roles

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#6]
Of course we should try do go heavy DRY and for that I propose we save all menus that have different items depending on user role (but still share something common) as lists in app state. Then whenever session is initialized and we have user role, we should dispatch action to filter those lists. 

Menu component will just get items to display from state without caring about role because items are already prepared.

**Comment by BrandonS6265** [comment]
So, as it stands now, we would essentially have 2 master lists, Agent and Partner. Then when user data is available we filter by role and then we keep that reference to the filtered list. Meanwhile the Menu component knows how to display every possible item but has no involvement with figuring out that list. 

That makes sense to me.

**Comment by marcindo** [comment]
I created one reducer for filtering with intention of storing all role dependent components, but as the app will grow I think it might be better to create separate reducers for each independent part with flat list.
Another concern is for routes which should also be somehow controlled so user cannot jump to wrong part from url.
Here I think simple main page/404 redirect would be best as I believe managing list of routes in state would be difficult and just plain wrong. So prob some HOC as wrapper for all routed components that performs redirect when when user shouldn't have access to the route
