### ISSUE TITLE
Currency in Org profile

### ISSUE THREAD

**Issue by kasfaw** [unicef/un-partner-portal#61]
Should a partner be able to select a currency when they indicate annual budget etc?

**Comment by kasialanecka** [comment]
maybe Partner could choose any currency and if it's not $, it will be always calculated by system into $? Or Partner should make calculation on his own and provide always in $?

**Comment by kasfaw** [comment]
What we have typically done is select the 3-letter code of a currency (i.e. USD, GBP, EUR) and included it as part of the figure (i.e. 10,000 USD). Let's see if there is a need for this or we can assume all to be in USD

**Comment by kasfaw** [comment]
@kasialanecka all currencies will be in USD
