### ISSUE TITLE
Application status display

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#613]
We have two fields for statuses of an application: 
- status, which can be preselected, reject, 
- application_status which has more advanced info like if application was declined.
However second field was recently added and this status is displayed only in some views, but not in the 'main' application list/details views for agency user.
This is  probably root cause of issues like this: https://trello.com/c/uH98cJxC/91-cfei-select
Application was declined, therefore doesn't appear in results tab, but agency user cannot really see that it was declined. We should display this extra status somewhere, it needs discussion with client

**Comment by marcindo** [comment]
linking #401 which is related

**Comment by brandinalexander** [comment]
#723 Just added from CFEI: Select ticket in Trello. See comment section, however, computer crashed while in the middle of discussing this ticket with the client. Waiting for a response to email for further details.
