### ISSUE TITLE
Add filter for applications list

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#642]
completely missing right now

**Comment by marcindo** [comment]
@brandinalexander @lkolacz  we need to revisit this as client has requested new fields in the filter that are not present on the mocks and not implemented in the backend

**Comment by brandinalexander** [comment]
Assuming this is related to the following:

Trello Ticket - https://trello.com/c/ytbVztKs/109-cfei-applications

DETAILS: 
The filters for shortlisting applications in a CFEI do not work. Additionally, they do not contain the information agreed to. For these filters we want the following information:
1. search
2. Country (From Profile)
3. Location (admin 1) (From country presence locations in profile)
4. Sectors and areas of specialization (from profile)
5. Population of concern (from profile)
6. Type of organization (from profile)

These filter should shortlist organizations that have this information on their profile.

**Comment by brandinalexander** [comment]
UPDATE: 

Just need to replace "Verification Status" w/ "Location" as seen in Mockups.

![ApplicationFilter_Mockup.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46c9848a2f8b80a89be0b04d8254fc802c54185e2607a83e60c7af6aaf50740b0a0c0abe4b4a5a4df9ac8d22aebf3b768d5f09edd16d5d71946c40acb9d40da313f871d51bdaebe5c01982fa3737e68c854e3b1f061b8ffe5a35a8904dc94abb.png)

**Comment by maxim-kht** [comment]
@marcindo Backend filter fields are added:
```
legal_name,
country_code
location
specializations
concern
type_of_org
```
