### ISSUE TITLE
Display logo thumbnail

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#672]
go to http://uat-unpartnerportal.westeurope.cloudapp.azure.com/
login as:
```
User name: hqa906@yahoo.com
Password: Unpp2017
```
and checkout accounts/me response, logo is sent but thumbnail is null

**Comment by lkolacz** [comment]
backend part is done ... there was a bug -> fixed !!!
thumbs will be generated after uploading new file
