### ISSUE TITLE
What file types support for CN template upload?

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#70]

**Comment by kasfaw** [comment]
@elyk at least PDF, doc, docx, Xls, Xlsx should be supported

**Comment by elyk** [comment]
Ok. cc @lkolacz

**Comment by brandinalexander** [comment]
Add special format for images.

**Comment by kenzo23312** [comment]
We need more information about specific file extensions.

To clarify:
- Should we present to user about file restrictions ? Tooltip / warning

**Comment by brandinalexander** [comment]
@kenzo23312 :

Allows the following:
PDF, Doc, DocX, XLS, XLSX, IMG, JPEG, JPG.

Maybe updated in the future*

Yes, please add a tooltip specifying the limitations.
