### ISSUE TITLE
CFEI: Select

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#723]
When a partner is awarded from the compare screen, the user is redirected to the application page which shows retract selection button. 

However, the results tab does not show that a partner is selected.

Please see the conversation between client and [KC] in comments below to add clarity.

Trello Ticket: https://trello.com/c/uH98cJxC/91-cfei-select

**Comment by brandinalexander** [comment]
Message response to Kyle on 10/13/17:

"...On the status change for expressions of interest, thank you for helping us to think these through. Yes, the aim was to have these map back nicely to the current statuses.

Application Under Review - Do they have to be undergoing assessment (preselected) or is this just any application submitted (our current pending). If the former, what is the default state after submission? The status “application under review” maps to the current “pending” and refers to the entire period of time between when the partner has submitted an application, and when the UN has made a selection. At the latter point in time, the status then becomes either “application unsuccessful” or “application successful.”

Application Unsuccessful - If the CFEI is closed and this was never actually reviewed (preselected/rejected), I'm assuming we will still default to this? YES

Application Successful - This maps back to our current Offer Made.

Selection Accepted - This maps back to our current Offer Accepted

Selection Declined - Maps back to Offer Declined

Selection Retracted - Maps back to Offer Withdrawn

Call Canceled -  My thoughts are this should be separate and handled similar to other completed states. The user should know what their application status was regardless of how the CFEI was completed (partners selected, canceled, no successful candidate) are my thoughts. This means applications need the same status toggle (active / completed) we have for CFEIs with agencies. Agree that this should be separate and handled similar to other completed/(now known as “finalized”) states. Actually, one of our comments in Invision was that “Finalized – CFEI canceled” should be one option under “Are you sure you want to finalize this CFEI?”
..."

![Status Conversation with Client.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46db809b379790e9ace6b155a14fe3953d4f287d6913aa3f78c5c024b64775154d435cec03070511afbd9b21b4b33575df5802e5d86a5973c53f11acb8801aed50eb208a1997aaaec81d9ebc6278bec1da0d2c1417198ef55c30a19a48c858fe4fe44b56a2017b.png)

**Comment by brandinalexander** [comment]
Sadly my computer crashed while in the meeting with the client so we were unable to have a successful conversation around this. I'm curious to see what Kyles response was to this email. I believe you may have access to pulling that conversation up if needed as the unpp@tivix address was Cc'd.

**Comment by marcindo** [comment]
This will be partially done in 757
