### ISSUE TITLE
CFEI: Award/Select and Retract

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#724]
A CFEI that was selected/awarded then subsequently retracted before the partner could accept or decline is showing three differnet statuses in different locations on the partner side:

1.) "Preselected" in the applications list 
2.) "pending" on the offers list
3.) and "withdrawn" on the dashboard.

When the CFEI was opened to the results page, the feedback for choosing and withdrawing was not there. 

Additionally there is no audit trail of the award and retraction.**

** Audit Trail is the Verification Status "History" - Please see image attached in comments.

Trello Ticket: 
https://trello.com/c/q6NHAL99/52-cfei-award-select-and-retract

**Comment by brandinalexander** [comment]
This may have been fixed in the most recent push. 

This is the "Audit Trail" Nadine was referring to. 

![Status Audit Trial.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00afb99a65e90012552ec9/125516c66e82c728ace21e0d46db809b379790e9aefcbb4ab01dc48620472b316546b3397f8fe62bab0021435a564bf94551574dfbff8e28a4b63c70885959bc806d5e22d42103eee9dc4be05ce36ade0d97bcae8b4bcae93824e4888f4d3e19071d8ef94f78.png)

**Comment by marcindo** [comment]
I believe that this issue is done then. Or is there anything else we should do @brandinalexander ?
