### ISSUE TITLE
CFEI: Manage Reviewers

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#726]
Unable to add reviewers to a CFEI.
Tested in UNICEF and TIVIX environment and same issue. See screenshot in Trello

Trello Ticket: https://trello.com/c/jxiv6Hha/124-cfei-manage-reviewers

**Comment by brandinalexander** [comment]
Comments From Trello & Slack:

Marcin Doliński
+nadinelivan I see that while request fails, the new reviewer is still added, can you confirm that's the case so while we investigate further? (No Reply from Client To Date)

While request fails and an error message is shown to the user, the new reviewer is in fact added, so that's not a real blocker, just confusing behavior. 

We would need some backend developer to investigate, as the error message is generic in prod environment.

Strangely enough, we should be getting an email from the server with detailed information, but this became broken around the beginning of December, so again, somebody needs to look at what is happening.

**Comment by mjaworski** [comment]
Is this still an issue? Works fine on dev for me, or does this occur for a specific user / use case?

**Comment by marcindo** [comment]
So far it only occurs in client prod and some testing strongly suggests it's related to notifications not being sent (which prob. raises the exception after database is changed)

**Comment by mjaworski** [comment]
by notifications here do we mean django emails? Is there a ticket specifying what more help is needed to help them set those up?

**Comment by marcindo** [comment]
Both email and in-app notifications are not send, client is using different mailing system that doesn't need authorization, so they just provide service port and host, that's all I know. Not sure if there is a ticket, maybe @maxim-kht knows more.
