### ISSUE TITLE
Identify Logic behind notifications for Client

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#735]
After our discussion with UNICEF, we should identify the logic created behind notifications on the portal and provide the client with the appropriate solution for setting up in their environment.

**Comment by mjaworski** [comment]
AFAIK notifications are sent through emails which uses Djangos built-in email sending support.

**Comment by maxim-kht** [comment]
We went over notification and email logic during the on-site. Related change: #856
