### ISSUE TITLE
Partner contact information - lack of validation

### ISSUE THREAD

**Issue by rkrupinski** [unicef/un-partner-portal#747]
When editing partner contact information, the backend validation is in place (`/api/partners/1/contact-information/`) for phone number and email, but the frontend permits any value for those fields.

**Comment by rkrupinski** [comment]
@brandinalexander Is there a phone number format that's correct throughout the app? @maxim-kht What do we use server-side to validate phone numbers against?

**Comment by maxim-kht** [comment]
@rkrupinski I see server validation is missing in many places where a phone number is used. Local DB fake data is using this format `+48 22 568 03 050`. I think we should use https://en.wikipedia.org/wiki/E.164, example `+482256803050`

**Comment by brandinalexander** [comment]
Something like this would be ideal. 
https://github.com/jackocnr/intl-tel-input

**Comment by mjaworski** [comment]
If it's not too late we should try switching to https://github.com/stefanfoulis/django-phonenumber-field for backend phone number storage

**Comment by rkrupinski** [comment]
I eventually used `^\+?[1-9]\d{1,14}$`

**Comment by rkrupinski** [comment]
https://github.com/unicef/un-partner-portal/pull/830
