### ISSUE TITLE
Partner Profile Creation - Invite Partners

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#75]
https://invis.io/9VCMWHXJS#/244894753_Agency_-_EIO_01_CFEOI_Open_Create_02

As an agency user, after I create a CFEI, I should be presented with a modal to select partners to send an invitation to apply. 

This ticket depends on: https://github.com/unicef/un-partner-portal/issues/74

**Comment by marcindo** [comment]
Closing as it is already done, along with #74
