### ISSUE TITLE
Profile: Saving

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#753]
Trello Ticket:
https://trello.com/c/t2CJnFSl/132-profile-saving

If user decides not to fill a section and save and continue to another section the attached error message received. User should be able to save and continue even if the section is incomplete

**Comment by brandinalexander** [comment]
From client: 
"...they can save and continue and come back and upload the document when they have it. As it is now, if the section is not fully completed, then they cannot save and continue"

Open Question:
Should we indicate that the field is missing or show no indicator at all, just a blank field?

Task: 
[ ] For now, I would remove the requirements from the profile fields so that the user can behave as described in Nadine's previous comment.

**Comment by brandinalexander** [comment]
Notification should show where error is by section / FIELD

USER SHOULD be able to SAVE & CONTINUE without proving all data in fields.

The profile will still be prevented from applying to CFEI applications until the profile is complete.

**Comment by kenzo23312** [comment]
We need to add check for dictionary fields for inner fields to mark section is_complete = false if they not filled in.

**Comment by kenzo23312** [comment]
Branch: bugfix/#753-optional-fields

Fields for check _is_complete flag:

-> Tab:  Contact information
Field: 'directors' basing on Bool from field 'have_board_directors'
Field: 'authorised_officers' basing on Bool from field 'have_authorised_officers'

-> Tab: Mandate and mission
Field: 'specializations' not basing on any Bool

-> Tab: Collaboration
Field: 'accreditations' basing on Bool from field 'any_accreditation'
Field: 'references' basing on Bool from field 'any_reference

-> Tab: Project implementation
Field: 'audits' (new field from task #716) basing on Bool from field 'regular_audited'
