### ISSUE TITLE
Add extra permissions for Partner detail views

### ISSUE THREAD

**Issue by maxim-kht** [unicef/un-partner-portal#772]
We need to filter queryset of available items for partner detail views based on which partner info they are allowed to see

Need to confirm exact rules with @marcindo

**Comment by mjaworski** [comment]
@maxim-kht I've started some work on a branch https://github.com/unicef/un-partner-portal/pull/833

@marcindo will you have time to spec out the filtering rules?

**Comment by marcindo** [comment]
Rules: 
- partner profile: /api/partners/:id/
  - non-ingo: visible to all partner members
  - ingo: hq users can view hq and all country profiles, country profiles should only view themselves and hq
   - agency user: can freely see all profiles
- partner profile summary: /api/partners/:id/summary - is used only by agency, but should implement same permissions as partner profile above
- project details: /api/projects/:id/
  - partner users can freely see all open CFEIs
  - partner users should only see direct selections to which organization was selected (that means ingo users can see DS for all ingo profiles)
- api/partners - restricted to agency only, but that is already done
- api/partners/short - as above

**Comment by maciej-jaworski** [comment]
No point in in finishing this, since permissions are being redone from ground up with CR1
