### ISSUE TITLE
Maps Library?

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#79]
We need to make a choice on which maps library to use:

- Google Maps
- Open Street Maps

There was some reservation in earlier discussions over using Google Maps, given it's not free. Need to look into Open Street Maps to see if it supports what we need.

**Comment by kasfaw** [comment]
@elyk also worth looking into which service makes it straightforward to remove a selected location from a map

**Comment by elyk** [comment]
Confirmation Unicef is fine moving forward with Google Maps.
