### ISSUE TITLE
CFEI - Open Selection Detail:Overview

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#80]
**Relevant Wireframe**
https://invis.io/9VCMWHXJS#/244899175_Agency_-_EIO_01_CFEOI_Open_Details_01

**Description**
This ticket entails building out the view associated with the above wireframe (Overview Section). This does not include API integration

**Comment by marcindo** [comment]
Delivered without timeline, and countries + sectors as that will come with separate updates
