### ISSUE TITLE
Missing filter for agency members

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#816]
missing filter in this screen:

https://projects.invisionapp.com/d/main#/console/11566713/246046888/preview

Backend task:
Add filter for endpoint: api/settings
to filter members by office name.

Continue on branch:
https://github.com/unicef/un-partner-portal/pull/819

**Comment by mjaworski** [comment]
@kenzo23312 Are you sure this is the correct URL you're talking about? Can't seem to find it.

**Comment by kenzo23312** [comment]
This one:

api/agencies/2/members/?name=a&page=1&page_size=10
