### ISSUE TITLE
Specific User Login Issue

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#824]
Trello Ticket:
https://trello.com/c/KRQOlvER/167-user-specific-login-error

At the login screen, after entering correct credentials for a specific user, the page seems to refresh (logs in then logs out) instead of accessing the Dashboard.

Username kenya906@yahoo.com
Password: Unpp2017

Please see screenshot in link:
https://www.evernote.com/l/AuWRsaBl45pK8aLmgSvnGO-No1fH8Iu4P1o

**Comment by mjaworski** [comment]
Some notes from quick testing: 
1. On the frontend piece we should definitely display an error message if any of the post login requests fail, currently only login error displays a message, any other requests failures just results in the described reload the page behaviour
2. It'll be hard to debug without access to logs / email errors from their servers
