### ISSUE TITLE
Update statuses in applications filter

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#872]
connects to https://trello.com/c/l1AsTxXR/196-profile-your-applications-filters

**Comment by marcindo** [comment]
@mjaworski we need to add filtering to the api/projects/applications/open/ so that status filter combines `status` and `applications_status` fields

**Comment by mjaworski** [comment]
1. `application_status` is not a database field, it is defined on a model, which wouldn't be a much of a  problem if it wasn't for:
2.  As seen in `apps/common/consts.py` `APPLICATION_STATUSES` and `EXTENDED_APPLICATION_STATUSES` do not match, so filtering both based off the same value doesn't make sense, would always return empty

Proposed solution options: 
1. Change property that is displayed in table to `status` from `application status`
2. Change options for filter on top of table to use `EXTENDED_APPLICATION_STATUSES` and implement custom `applications_status` filter on the api/projects/applications/open/ endpoint to use those values.

**Comment by brandinalexander** [comment]
Decided to go with Solution # 2
