### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#890]
Trello Ticket:
https://trello.com/c/eKC2uEJe/201-notifications

Partner side notifications not working. tested in both UNICEF and staging environment with the same result.

No notifications (both in the portal and emails) sent if partner was invited on a CFEI or if the were sent a direct selection

**Comment by mjaworski** [comment]
@marcindo As an agency user when I click invite partners in a CFEI, select a couple and click ok empty list is sent to backend 
<img width="224" alt="screen shot 2018-01-18 at 3 15 04 pm" src="https://user-images.githubusercontent.com/1492815/35102169-648a7332-fc62-11e7-9f03-e0478b233900.png">
