### ISSUE TITLE
Profile: Funding tab: budget

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#902]
Trello Ticket:
https://trello.com/c/m5EHRGSp/208-profile-funding-tab-budget

Organization created in 2017, when inputting the 2018 budget, the profile does not save the information and keeps showing the tab as incomplete. This makes the profile show as incomplete.

**Comment by brandinalexander** [comment]
May be related to #858 & #851

**Comment by marcindo** [comment]
@mjaworski according to comments in https://trello.com/c/B0M7IsP5/170-profile-saving budget of country profile should be completely separated

**Comment by mjaworski** [comment]
@marcindo it seems only a frontend change, it needs to stop using `hq_budgets` and just use `budgets` for every profile.
