### ISSUE TITLE
CFEI: Review Tab

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#913]
Trello Ticket:
https://trello.com/c/RTlYVqEQ/210-cfei-manage-reviewers

Logged in as an invited reviewer for the CFEI and cannot access the application tab or pre-selected list tab. (see screenshot)

Login: *****************
Password: ***************

**Comment by brandinalexander** [comment]
Please confirm if the tabs are "phased in" - once a pre-required tab is completed, a new tab is made present?

ie: Applications > Preselected > Results

Per Discussion 1/23: 
It appears that the Results tab is not present until the application is finalized. However, the user (ie: CFEI focal point, CFEI assessment Team [reviewer] ) should be able to access the Results page prior to making a final decision.

After the CFEI is finalized, all other users should have the ability to review the results tab.

**Comment by marcindo** [comment]
No, each tab has separate permission depending on user status.
Indeed owners and focal points couldn't see those tabs if they were just editors so I changed that, and enabled results to all reviewers too.
So to sum up: 
- applications and preselected: visible to all agency admins, cfei owner, focal points and reviewers
- results: visible to all agency admins, cfei owner, focal points and reviewers, but also all users if cfei is finalized
And agency reader currently cannot be added as focal point or reviewer, and cannot create cfei as well
