### ISSUE TITLE
No notification for new focal point

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#914]
If agency user is added as cfei focal point, notification isn't send to this user (it does happen when user is added as reviewer)
Inconsistent behavior, if the notification template exists it should be enabled, but if there is none @brandinalexander  we need to ask client for clarification

**Comment by brandinalexander** [comment]
@marcindo  
To clarify, are we confirming if a notification should be sent to a user when they are added as a CFEI Focal Point? 

We have the ability to notify the user of this change already built, however, it is inactive?
