### ISSUE TITLE
Partner Directory Filter

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#94]
Need to add more filter options to partner directory above what is currently there. 

See https://www.evernote.com/l/AKKSbBSW_INF5rdsc6Ta_Wg6OkgiiTE8aCQ as options

**Comment by kasialanecka** [comment]
On this screen - https://invis.io/9VCMWHXJS#/244900463_Agency_-_Partners_01 or on Dashboard or both?

**Comment by elyk** [comment]
Just on that screen (Partner Directory)

**Comment by kasialanecka** [comment]
@kasfaw do we need all filters here as shown on this screenshot?

**Comment by kasfaw** [comment]
@kasialanecka the following for now. rest seems specific to UNHCR, but we can get clarification next week:

Legal Name / Acronym (as search field)
Verification Status
Partner Type
Country of Operation
Sector/Area of Specialisation
Primary Persons of Concern

**Comment by kasialanecka** [comment]
updated: https://invis.io/9VCMWHXJS#/244900463_Agency_-_Partners_01

changes to your list:
First is just a search field
Partner Type -> Organization Type (as a label of column suggests)
Country of Operation -> Country (our every filter has just this as a label)
Primary Persons of Concern -> Populations of concern (this is what we have in a Partner's Profile)
