### ISSUE TITLE
Hidden reviews

### ISSUE THREAD

**Issue by marcindo** [unicef/un-partner-portal#965]
When reviews are hidden, apparently they are still counted for assessments_is_completed field in application model
and review_progress field in applications list model

**Comment by marcindo** [comment]
When reviews are hidden, apparently they are still counted for assessments_is_completed field in application model

**Comment by mjaworski** [comment]
Added some tests on a branch, but everything seems to be working fine even before the changes. Are we sure this is not a browser caching issue?
