### ISSUE TITLE
CFEI: Invite partner email notification

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#986]
Trello Ticket:
https://trello.com/c/zOG4Jtm8/219-cfei-invite-partner-email-notification

The email notification that goes to a partner when they are invited to a CFEI gives the Tivix lab URL as highlighted in the screenshot

**Comment by mjaworski** [comment]
Look at the latest comment in the ticket, it's a whole new bug that should've been reported as a separate issue. After checking seems it's a frontend issue, reassigning.
