### ISSUE TITLE
Assign Roles to Users

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#994]
Ability to assign roles to users in the organization.

Ability for the `HQ Editor` and `Administrator` of participating agencies to assign additional roles to the agency’s users.

https://docs.google.com/spreadsheets/d/1CPf_hWeTwPXrVPd-suggavA7GFoLdJGxx1oROz2unnY/edit?usp=drive_web&ouid=109331275056351314446

**Comment by maciej-jaworski** [comment]
To clarify - we're only doing role changes, not permission changes.

**Comment by brandinalexander** [comment]
Correct. This should just read as roles. I will edit for clarity.
